### ISSUE TITLE
Unable to link individual enchants from Skillet book

### ISSUE THREAD

**Issue by nikachelle** [b-morgan/Skillet-Classic#100]
Hello! I am currently unable to link any particular enchant from the Skillet book like I used to. I checked and did not see anyone else logging this complaint, so thought I would post here. Thank you for your time, and for this wonderful addon - it's fantastic!

**Comment by b-morgan** [comment]
Enchanting is going to be the death of me! Blizzard changed Enchanting from a Craft in BCC to a TradeSkill in Wrath.

The question I have for you is how did you used to do it?

To link the recipe right-click on the enchant on the recipe (left) side of the Skillet-Classic frame and then click "Link recipe". Shift-click on the icon on the detail (right) side of the frame will link the item if there is one (enchants don't produce "items" but some recipes do like Wizard Oil). Alt-click on the icon on the detail (right) side of the frame will link all the reagents required or shift-click each individual reagent.

**Comment by b-morgan** [comment]
In Burning Crusade Classic, shift-click on the detail (right) icon did link the enchant recipe. I believe I've fixed it in Wrath Classic. It will be in the next build. Not sure if that will be an alpha, beta, or the next release.

**Comment by nikachelle** [comment]
AHA. I did used to shift click the enchant. I was unaware of the right click to Link recipe. Thank you! The shift click would be great in the next launch. Thank you!

**Comment by b-morgan** [comment]
[Skillet-Classic-1.49-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/3990686) contains this fix.
