### ISSUE TITLE
Feature Request: Load Plugins automatically

### ISSUE THREAD

**Issue by hogfather-wow** [b-morgan/Skillet-Classic#101]
I have written my own skillet plugin. But every time when I update the addon I have to add the plugin in the TOC file.

Would it be possible to load all plugins located in the Skillet-Classic/Plugins folder automatically?
This would make it unnecessary to list them all in the TOC file.

**Comment by b-morgan** [comment]
Unfortunately, it is not possible for addons to selectively load other addons. However, plugins for Skillet-Classic don't have to reside in the `Plugins` folder or be included in the TOC file.

Here is an example, [SkilletTSMPlugin-v1.0.zip](https://github.com/b-morgan/Skillet-Classic/files/9566156/SkilletTSMPlugin-v1.0.zip)

The magic is `## Dependencies: Skillet` in the TOC file. The namespace (which you are already using) and the register functions in `...\Skillet-Classic\SkilletPlugin.lua` (there's an AddRecipeSorter function defined in `...\Skillet-Classic\UI\Sorting.lua`. This should all be documented in `...\Skillet-Classic\ThirdPartyHooks.lua`.

What does your plugin do?

**Comment by hogfather-wow** [comment]
Thanks for your answer @b-morgan! That is very cool I didn't know that I can completely put my plugin outside of the skillet-classic folder.

_What does your plugin do?_
My Addon tracks the items, that I auction and that I have in the Inventory of my chars. The Skillet Plugin of my Addon shows the number of my existing items as Prefix before each item. With this I know what gems or glyphs I not have as auctions or in my inventory somewhere and can build the queue quickly to refill the AH with my stuff ;-). With the combination of the suffix of auctinator, I can see what Item I have not in the AH and what profit I would get for this Item.

![image](https://user-images.githubusercontent.com/88636256/190623337-05b9704b-c0a6-4e6e-904f-19660dd04b77.png)

 
![image](https://user-images.githubusercontent.com/88636256/190623507-2709a29e-86ad-42e8-a66a-b7fd9cc53429.png)

**Comment by b-morgan** [comment]
Very nice! Excellent way to use both the prefix and suffix.
