### ISSUE TITLE
Suggestion: Only type in the search bar if the search bar is selected

### ISSUE THREAD

**Issue by rushtothesun** [b-morgan/Skillet-Classic#102]
If you type text in the search bar, for example bracer, and then want to open your bags or character sheet with a keybind you can't because the search bar is always selected. So if I type bracer to look for my Enchant Bracer recipes and then press B to open my bags I won't be able to open my bags because the B gets put in the search bar.

Is it possible to make it so that if you click out of the search bar it gets deselected?

**Comment by b-morgan** [comment]
The Skillet-Classic Search is an EditBox and behaves the same way as chat and all the other addon EditBoxes I was able to check. I'm not sure I want to invent a new UI element with different behavior. You can type <Enter> or <Escape> to clear the focus.
