### ISSUE TITLE
[bug] the qeue only stacks if you have materials once, after selecting another recipe, it won't

### ISSUE THREAD

**Issue by Raithen88** [b-morgan/Skillet-Classic#107]
Hi,
there is the following bug:
If you select an enchantment you have the materials for: It can stack up!
If you then select another enchantment, it won't, even if you also have the materials for it.

**Comment by b-morgan** [comment]
I can't reproduce this. On my system, with or without materials, multiple presses of the Queue button result in adding to the existing entry in the queue.

When you have a failing case, please type `/skillet printqueue` and show me the text output (until the next build, you will probably have to take a screenshot with chat output displayed). I've changed this command to output to chat and to the debug log (if enabled) in the next build).

Please try with lower level, simple enchants.

**Comment by b-morgan** [comment]
This is actually a "feature". To eliminate this behavior, uncheck the option "Queue craftable reagents".
