### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Raulfin** [b-morgan/Skillet-Classic#109]
I do a lot of crafting on a lot of toons, and generally have most profs on any server I play on. Collapsing and expanding groups is a big help in getting to a recipie I need, but having to click the tiny arrow can kinda suck sometimes;

![WowClassic_FJljNj3YcS](https://user-images.githubusercontent.com/7994405/191076124-27bcd954-c850-4b09-8813-560cc9018a0d.png)

Would be a big help if clicking the group header also expand/collapes the group instead of just highlighting it;

![WowClassic_mAVPvdvP8w](https://user-images.githubusercontent.com/7994405/191076707-c6ed6bed-b501-4eaa-9715-5b82a42f6457.png)
Even turned off the fancy curser for you :)

**Comment by b-morgan** [comment]
The little arrows have one set of click assignments and the group headers have a separate set of click assignments. This separate set of click assignments is to support Custom Groups.

The headers and the recipes use left-click to select, control-left-click to select multiple, shift-left-click to select all between similar to how editors work. Right-click will bring up a context menu which varies depending on where you are.

For example, Click the little arrow (kinda sucks its so small :-) ) next to Grouping and select New. Left-click on Food & Drink and then right-click and select Copy. In the Grouping dropdown, select Custom. In the empty space right-click and select Paste.

**Comment by b-morgan** [comment]
Unfortunately, this enhancement cannot be implemented
