### ISSUE TITLE
WOTLK Error

### ISSUE THREAD

**Issue by SegoItCh** [b-morgan/Skillet-Classic#110]
2x Skillet-Classic\Inventory.lua:55: attempt to perform arithmetic on field 'numMade' (a nil value)
[string "@Skillet-Classic\Inventory.lua"]:55: in function `InventoryReagentCraftability'
[string "@Skillet-Classic\Inventory.lua"]:195: in function `InventoryScan'
[string "@Skillet-Classic\SkilletData.lua"]:1089: in function <Skillet-Classic\SkilletData.lua:660>
[string "@Skillet-Classic\SkilletData.lua"]:1149: in function `RescanTrade'
[string "@Skillet-Classic\Skillet-30400.nil.lua"]:1190: in function `SkilletShowWindow'
[string "@Skillet-Classic\Skillet-30400.nil.lua"]:900: in function `TRADE_SKILL_UPDATE'
[string "@Skillet-Classic\Skillet-30400.nil.lua"]:1158: in function `SkilletShow'
[string "@Skillet-Classic\Skillet-30400.nil.lua"]:967: in function `?'
[string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Bagnon\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@FrameXML\SecureTemplates.lua"]:343: in function `handler'
[string "@FrameXML\SecureTemplates.lua"]:625: in function <FrameXML\SecureTemplates.lua:569>
[string "=[C]"]: ?
[string "@FrameXML\SecureHandlers.lua"]:266: in function <FrameXML\SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML\SecureHandlers.lua"]:296: in function <FrameXML\SecureHandlers.lua:279>
[string "=(tail call)"]: ?

**Comment by b-morgan** [comment]
Please try [Skillet-Classic-1.49-alpha7](https://www.curseforge.com/wow/addons/skillet-classic/files/3997024).

**Comment by b-morgan** [comment]
Skillet-Classic-1.49 has been released.
