### ISSUE TITLE
Enchant Vellum button request

### ISSUE THREAD

**Issue by Kaosian** [b-morgan/Skillet-Classic#111]
Can you add an enchant vellum button please

**Comment by b-morgan** [comment]
If you can provide (and maintain) a table of which of the six vellum types should be used for each enchant then I can provide a "button" (which actually already exists). Actually, I can default to one of the six vellums so I just need a table for the other five.

**Comment by Kaosian** [comment]
Armor Vellum   (Only able to absorb enchantments with no level restrictions.")
Armor Vellum II  (Only able to absorb enchantments with a level restriction of 35 or lower.)
Armor Vellum III ( Only able to absorb enchantments with a level restriction of 60 or lower.)

Weapon Vellum   (Only able to absorb enchantments with no level restrictions.")
Weapon Vellum II  (Only able to absorb enchantments with a level restriction of 35 or lower.)
Weapon Vellum III ( Only able to absorb enchantments with a level restriction of 60 or lower.)

not sure but their is one that is in retail only but does not work at all in classic. https://www.curseforge.com/wow/addons/enchant-vellum

**Comment by b-morgan** [comment]
I found the data I need so I will build an alpha release soon.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.50-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/4005234) contains the ability to Alt-Click (or Right-Click) on the Enchant button or the Process button (if you have an enchant at the top of the queue). If you have the materials and the correct type of vellum in your inventory then Skillet-Classic will apply the enchant to the vellum to produce a scroll.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.50-alpha2](https://www.curseforge.com/wow/addons/skillet-classic/files/4005348) contains an option to use a higher level vellum if the correct vellum isn't available.

**Comment by Raulfin** [comment]
Alt+Left click does apply the enchant to the vellum, but right click does not.

**Comment by Raulfin** [comment]
looked at BugSac and saw this, was thrown silently;

```
1x Skillet-Classic\SkilletData.lua:419: bad argument #1 to 'tostring' (value expected)
[string "=[C]"]: in function `tostring'
[string "@Skillet-Classic\SkilletData.lua"]:419: in function `GetAutoTargetItem'
[string "@Skillet-Classic\SkilletQueue.lua"]:414: in function `ProcessQueue'
[string "@Skillet-Classic\SkilletQueue.lua"]:488: in function `CreateItems'
[string "@Skillet-Classic\SkilletQueue.lua"]:529: in function `EnchantItem'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
```

**Comment by b-morgan** [comment]
> Alt+Left click does apply the enchant to the vellum, but right click does not.

This will be fixed in the next build. The `Enchant` button was missing right click, the `Process` button correctly handled both.

> If the correct vellum is not present, and a higher, or no other, vellum is present then alt clicking is the same as a left click

This is how it works now. How would you like it to work?

> looked at BugSac and saw this

Not sure about this one but I changed to code a bit for the next build.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.50-alpha3](https://www.curseforge.com/wow/addons/skillet-classic/files/4007227) will cancel an alt-click (or right-click) enchant if no useable vellum is found. A message is sent to chat.

**Comment by Raulfin** [comment]
looks to all work :)

**Comment by b-morgan** [comment]
Thanks for helping to test. Please open a new issue if you do find any bugs.
