### ISSUE TITLE
can't open 1.50a4

### ISSUE THREAD

**Issue by Raulfin** [b-morgan/Skillet-Classic#113]
Just updated from 1.50a2 to 1.50a4 and can no longer open any craft window on any toon.

renamed Skillet-Classic.lua in account saved variables with no change. Back versioned to 1.50a3 and it opens again. Downloaded from Curse app.

**Comment by veiset** [comment]
I'm also having the same issue.

**Comment by b-morgan** [comment]
Two choices... Install [Skillet-Classic-1.50-alpha5](https://www.curseforge.com/wow/addons/skillet-classic/files/4008274) or install the addon Altoholic.
