### ISSUE TITLE
Skillet errror when LFG

### ISSUE THREAD

**Issue by gelsbern** [b-morgan/Skillet-Classic#115]
When I enter Looking For Group, I get the following:

`2x [ADDON_ACTION_BLOCKED] AddOn 'Skillet-Classic' tried to call the protected function 'Search()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `Search'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:225: in function `LFGBrowse_DoSearch'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:178: in function `SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua"]:67: in function <...s\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:49`

I am not crafting at the time, and the skillet window is not open when this occurs.

**Comment by b-morgan** [comment]
Is this reproducable?

I can assure you that Skillet-Classic has nothing to do with LFG. I'd say this was a side effect of the way ACE libraries determine which addon has the most recent version of each library but there are no ACE calls in the traceback.

Unless you can generate a reproducible case, there's nothing I can do with this error

**Comment by gelsbern** [comment]
It happens every time, but I'll see if I can generate more info

**Comment by Raulfin** [comment]
i just came to report this also, was bouncing in dala and grp lead put us in Q and it popped up.

```
Message: ADDON_ACTION_BLOCKED: Skillet-Classic tried to call the protected function 'Search()'.
Time: Wed Oct  5 06:58:13 2022
Count: 1
Stack: ADDON_ACTION_BLOCKED: Skillet-Classic tried to call the protected function 'Search()'.
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...vUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `Search'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:225: in function `LFGBrowse_DoSearch'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:178: in function `SearchActiveEntry'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua"]:67: in function <...s\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:49>

Locals: <none>
```

**Comment by b-morgan** [comment]
I'd say this was a side effect of the way ACE libraries determine which addon has the most recent version of each library. @Raulfin shows AceEvent-3.0 and ElvUI in the traceback so I'd look there.
