### ISSUE TITLE
The WotLK tailoring "enchants" do not display useful tooltips.

### ISSUE THREAD

**Issue by Elberet** [b-morgan/Skillet-Classic#116]
Wrath added several recipes to the tailoring profession that work much like enchanting recipes: select recipe, click the 'craft' button to get a targeting cursor, then click the tailor's cloak or pants to apply a profession-specific unique enchantment.

Affected recipes:
- https://www.wowhead.com/wotlk/spell=55769/darkglow-embroidery
- https://www.wowhead.com/wotlk/spell=55642/lightweave-embroidery
- https://www.wowhead.com/wotlk/spell=55777/swordguard-embroidery
- https://www.wowhead.com/wotlk/spell=56034/masters-spellthread
- https://www.wowhead.com/wotlk/spell=56039/sanctified-spellthread

The right part of the Skillet window shows the required reagents, but since the recipe does not actually create an item, the icon does not have any tooltip whatsoever:

![image](https://user-images.githubusercontent.com/361662/193479204-090bda69-640c-4181-b711-73d29f04293d.png)

While minor, this forces slightly forgetful tailors like myself to constantly look up Master's and Sanctified Spellthread whenever they receive new pants! Truly a tragedy! 😢

**Comment by b-morgan** [comment]
I haven't started leveling my tailor in Wrath yet so I'll need your help to fix this. First, it looks to me that you are not using the enUS client. What is your locale? Just to be sure, what version of Skillet-Classic?

I need you to mouse over each of these recipes in the Skillet-Classic recipe list, take a screenshot, and upload it here. Also upload your global saved variables file, Skillet-Classic.lua. You will have to zip the file or add a .txt extension as github doesn't allow .lua extensions.

I may need you to enable Skillet-Classic's debugging but I'll decide that after I see the above.

**Comment by b-morgan** [comment]
Please type "/skillet warnshow on", "/skillet debuglogging on", "/skillet tabledump on",  and "/skillet debuglevel 4" and let me know if you get any Warnings from Skillet-Classic.

**Comment by b-morgan** [comment]
Skillet-Classic-1.51 fixes this error.

**Comment by Elberet** [comment]
I guess that means you got your tailor to 80? 😄 Thanks for the quick fix!

**Comment by b-morgan** [comment]
No, I got my tailor to 405... He is still level 70... Just bought lots of Frostweave Cloth from the AH (about 1,000g worth).
