### ISSUE TITLE
[request][enhancement] sorted shopping list in alphabetical order

### ISSUE THREAD

**Issue by Raithen88** [b-morgan/Skillet-Classic#119]
Hi,
small request here. Is it possible to get a checkbox or simple possibility to add "sort shopping list items in alphabetical order" ?
This would be great, since the shoppinglist order and auctionator app order could match.

Thanks!

**Comment by b-morgan** [comment]
So what you are really asking is for the check box, "Order by item" to actually work!

**Comment by b-morgan** [comment]
Replace `...\Addons\Skillet-Classic\UI\ShoppingList.lua` with the contents of [ShoppingList.zip](https://github.com/b-morgan/Skillet-Classic/files/9802838/ShoppingList.zip) and let me know if that's what you want.

**Comment by Raithen88** [comment]
Hey!
Your modified ShoppingList.lua file fulfills my requirement perfectly! This was a very quick solution. Bow to you!

**Comment by b-morgan** [comment]
[Skillet-Classic-1.53-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/4033213) contains this fix.
