### ISSUE TITLE
Engineering Item Improvements show no tooltip

### ISSUE THREAD

**Issue by b-morgan** [b-morgan/Skillet-Classic#120]
In the original gui, some eng patterns - the item improvements - do not have description on the item/icon itself, but in a text under it. Skillet does not use those texts and so those patterns have no description at all. E.g. Nitro Boosts.

v 1.50 (30400)

**Comment by b-morgan** [comment]
@Met7, I believe this is fixed in the latest [Skillet-Classic](https://www.curseforge.com/wow/addons/skillet-classic/files). Please install [Skillet-Classic-1.53-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/4033213) and let me know ASAP.

I was planning to release 1.53 today but I'll hold off for 24 hours or until I hear from you

**Comment by Met7** [comment]
Sorry for the wrong branch.
The texts are displayed now.
But the popup should have some fixed width and break the text. Now it stretches in long lines over most of the screen.
I won't be able to answer after this for the next few days.

**Comment by b-morgan** [comment]
This should be fixed in [Skillet-Classic-1.53](https://www.curseforge.com/wow/addons/skillet-classic/files/4035520).
