### ISSUE TITLE
[Enhancement] Pull Tools from Bank

### ISSUE THREAD

**Issue by roweboy1974** [b-morgan/Skillet-Classic#124]
Is it possible to also pull the needed tools out of the bank for the queued recipe (ie inking set, blacksmith hammer, etc)

**Comment by b-morgan** [comment]
If I add missing tools to the shopping list when the recipe is queued, then anywhere the shopping list is opened will attempt to retrieve them. This includes merchants, bank, guild bank, and the auction house.

Is this acceptable?

**Comment by b-morgan** [comment]
[Skillet-Classic-1.54-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/4055343) contains an option (Queue tools) and the code to do this.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.54-alpha2](https://www.curseforge.com/wow/addons/skillet-classic/files/4056338) contains a minor fix.

**Comment by roweboy1974** [comment]
Yes... that would be acceptable...

**Comment by b-morgan** [comment]
Let me know if the alpha code works for you.
