### ISSUE TITLE
[suggestion] Add a new column in the skillet window to show "number of sold products" 

### ISSUE THREAD

**Issue by Raithen88** [b-morgan/Skillet-Classic#125]
Hi!
I have an idea to improve skillet a little bit.
The idea is: A new coloum which shows the #number of sold products.

The number could be shown here: http://puu.sh/Jqts8/bcaacfbd96.jpg

Problem is:
I don't know where you could get this information from. "Auctioneer" has a beancounter plugin, but the last time i tried it, alot of data became corrupt and some addon configurations crashed. Perhaps you have an idea?

**Comment by b-morgan** [comment]
The Skillet-Classic recipe list has a fixed number of columns and it would be difficult to add anymore, particularly special purpose ones like this.

However, the recipe name is broken down into three areas, the prefix, name, and suffix. Skillet-Classic plugins use the prefix and suffix areas (and an area called extra text on the details side). Only one plugin can be assigned to each of the prefix and suffix areas but multiple plugins can add extra text.

The "number of sold products" sounds like an AH related thing and therefore would be something one of the AH plugins would have to provide. There is a BeanCounter plugin.

Note that Skillet-Classic plugins were, for the most part, written by others and submitted for inclusion. I maintain them as best I can but major enhancements are not something I'm interested in. If you do the research and find the data you wish to display, I might be able to help you incorporate into the appropriate AH plugin.

**Comment by b-morgan** [comment]
You might want to check out the addon Journalator (same author as Auctionator). Journalator can add a sale rate percentage to tooltips and when I asked the author, he is willing to add an API for that information.

**Comment by b-morgan** [comment]
If you install the addon [Journalator](https://www.curseforge.com/wow/addons/journalator) and replace `...\Skillet-Classic\Plugins\Auctionator.lua` with contents of the attached zip file you can enable (plugin options) some statistics on your AH activity (after you collect some with the addon that is).
[Auctionator.zip](https://github.com/b-morgan/Skillet-Classic/files/9923852/Auctionator.zip)

This uses the Journalator statistics that are (optionally) added to the tooltip. See the attached "Hearty Rino" information (the BeanCounter plugin adds the count you are interested in to the recipe details).

![Journalator](https://user-images.githubusercontent.com/1547854/199594885-98d6a838-3e0f-4b91-a346-c9ac5d06bf07.jpg)

**Comment by b-morgan** [comment]
See #126 for an updated plugin.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.54-alpha4](https://www.curseforge.com/wow/addons/skillet-classic/files/4066399) uses the new Journalator API (if available). It also adds another plugin option that will show the actual success count instead of the success rate (if the API is available).
