### ISSUE TITLE
[issue] Please hide "[unbekannt]" - localization error with journalator / skillet plugin

### ISSUE THREAD

**Issue by Raithen88** [b-morgan/Skillet-Classic#126]
Hey!
I tested your plugin from journaltor. Unfortunatelly, there is a big german [unbekannt] if the % of sold items is unknown. Can u fix it the way, that this string simply won't show up?

Here's a picture of the word I want to hide.
http://puu.sh/JqDtg/a583a6beea.jpg

Thank you!

**Comment by b-morgan** [comment]
This version of the plugin should work better, [Auctionator.zip](https://github.com/b-morgan/Skillet-Classic/files/9931878/Auctionator.zip). Copy the contents of this zip file into `...\Interface\Addons\Skillet-Classic\Plugins`.

**Comment by Raithen88** [comment]
Issue solved.
