### ISSUE TITLE
[request][journalator plugin]  New sort function

### ISSUE THREAD

**Issue by Raithen88** [b-morgan/Skillet-Classic#127]
Hi!

can you add a sort option to sort for "most sold" via "sort by suffix"-option?

**Comment by b-morgan** [comment]
[Skillet-Classic-1.56-alpha2](https://www.curseforge.com/wow/addons/skillet-classic/files/4076730) contains this sorter.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.56-alpha3](https://www.curseforge.com/wow/addons/skillet-classic/files/4076866) contains a sorter that should work for enchanting.

**Comment by b-morgan** [comment]
After fixing a typo it works.
