### ISSUE TITLE
[request] new sort option: ATR: immediate purchase (Buyout)

### ISSUE THREAD

**Issue by Raithen88** [b-morgan/Skillet-Classic#128]
Hi,
since there is a sort option for "most profit" and since last update "most sold recipes", I'd like to ask, if it's possible, to add a new sort function, showing the "highest prices in the AH".

So, just sort for the price of recipes or items in the, not the profit.
This could help to identify items, where a good ressource managing is high valuable.

If you want to: contact me to test it :)

**Comment by b-morgan** [comment]
I'm afraid I don't understand this request. Where does the data come from?

**Comment by Raithen88** [comment]
This data here:
https://puu.sh/JsfXE/9e7578d605.jpg

**Comment by Raithen88** [comment]
Yep, with your plugin, it works.
Thanks!

**Comment by b-morgan** [comment]
Please provide more details for "The sort won't work".

**Comment by b-morgan** [comment]
[Skillet-Classic-1.57](https://www.curseforge.com/wow/addons/skillet-classic/files/4123559) contains (a working version) of this issue
