### ISSUE TITLE
Occasional Lua error when using group finder in Classic Wrath

### ISSUE THREAD

**Issue by robmonte** [b-morgan/Skillet-Classic#129]
Sometimes when listing myself in the group finder in Classic Wrath, I get the following Lua error. It doesn't always occur which is strange, perhaps it is only after I've recently crafted an item through Skillet? Not entirely sure.

Error:
```
Message: [ADDON_ACTION_BLOCKED] AddOn 'Skillet-Classic' tried to call the protected function 'Search()'.
Time: Tue Nov 29 18:54:53 2022
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Skillet-Classic' tried to call the protected function 'Search()'.
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:178: in function `SearchActiveEntry'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua"]:67: in function <...s\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:49>

Locals: <none>
```

Not sure the relation between Skillet and LFG frames that could be causing this.

**Comment by b-morgan** [comment]
The Skillet-Classic code does not contain any calls to `Search()` so I don't believe it can be Skillet-Classic.

I looked at the Blizzard code (if you open WoW with `-console` on the command line, type `~` to open the console, and type `exportInterfaceFiles code` you get a copy of Blizzard's code in the _classic_ folder). Their lua code doesn't contain a call to `Search()` so I'm thoroughly confused :-)
