### ISSUE TITLE
Item decomposition not working correctly in queue when needed items to make other items for the recipe selected

### ISSUE THREAD

**Issue by fireboy92k** [b-morgan/Skillet-Classic#13]
Below is a sample from Leatherworking.  Quantities needed are incorrect and some items are not decomposed to parts.

On another toon with engineering for most recipes, it seems to be showing the component items as whole components vs the parts needed to make them if they are not in inventory.  For instance, trying to create an Unstable Trigger only adds 'unstable trigger' to the queue and say 'missing regent: mageweave' vs. showing the components of the recipe to add to the shopping list.

![image](https://user-images.githubusercontent.com/56378639/120087632-94a01780-c0b7-11eb-9ae1-f06e3ca284d2.png)

**Comment by b-morgan** [comment]
Pick a quiet place so there is little, if any, chat output. I step inside an instance (RageFire Chasm if Horde, Deep Run Tram if Alliance) but almost anywhere except inside a city (i.e. no Trade - City chat).

1. Click Clear.
2. Click Shopping List.
3. Arrange the Skillet-Classic frame and the Shopping List frame so I can see both.
4. Type "/skillet printqueue" (nothing should happen).
5. Take a screenshot.
6. Select "Devilsaur Leggings" and click Queue (once).
7. Type "/skillet printqueue".
8. Take a screenshot.

Post both screenshots without editing, please.

**Comment by fireboy92k** [comment]
First picture as requested
![image](https://user-images.githubusercontent.com/56378639/120092561-d5ad2180-c0e1-11eb-8108-e44a37ee86de.png)

**Comment by fireboy92k** [comment]
Second picture as requested:
![image](https://user-images.githubusercontent.com/56378639/120092614-2a509c80-c0e2-11eb-966d-969c34628592.png)

And here is a copy of the log data:
Skillet-Classic: PrintQueue(nil)
Flanagan has gone offline.
[Rotorua] has come online.
Skillet-Classic: ShowReagentDetails()
Skillet-Classic: ConfigureRecipeControls()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: QueueItems(1)
Skillet-Classic: QueueCommandIterate(Devilsaur Leggings, 1) currentTrade= 2108
Skillet-Classic: QueueAppendCommand({table}, true)
Skillet-Classic: recipe= {table}
Skillet-Classic: queueAppendReagent(8170, 30, true), name= Rugged Leather
Skillet-Classic: QueueCommandIterate(Rugged Leather, 17) currentTrade= 2108
Skillet-Classic: QueueAppendCommand({table}, true)
Skillet-Classic: recipe= {table}
Skillet-Classic: queueAppendReagent(4304, 102, true), name= Thick Leather
Skillet-Classic: QueueCommandIterate(Thick Leather, 99) currentTrade= 2108
Skillet-Classic: QueueAppendCommand({table}, true)
Skillet-Classic: recipe= {table}
Skillet-Classic: queueAppendReagent(4234, 594, true), name= Heavy Leather
Skillet-Classic: QueueCommandIterate(Heavy Leather, 332) currentTrade= 2108
Skillet-Classic: QueueAppendCommand({table}, true)
Skillet-Classic: recipe= {table}
Skillet-Classic: queueAppendReagent(2319, 1660, true), name= Medium Leather
Skillet-Classic: QueueCommandIterate(Medium Leather, 1341) currentTrade= 2108
Skillet-Classic: QueueAppendCommand({table}, true)
Skillet-Classic: recipe= {table}
Skillet-Classic: queueAppendReagent(2318, 5364, true), name= Light Leather
Skillet-Classic: QueueCommandIterate(Light Leather, 5278) currentTrade= 2108
Skillet-Classic: QueueAppendCommand({table}, true)
Skillet-Classic: recipe= {table}
Skillet-Classic: queueAppendReagent(2934, 15834, true), name= Ruined Leather Scraps
Skillet-Classic: AddToQueue({table})
Skillet-Classic: AdjustInventory()
Skillet-Classic: ScanQueuedReagents()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: AddToQueue({table})
Skillet-Classic: AdjustInventory()
Skillet-Classic: ScanQueuedReagents()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: AddToQueue({table})
Skillet-Classic: AdjustInventory()
Skillet-Classic: ScanQueuedReagents()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: AddToQueue({table})
Skillet-Classic: AdjustInventory()
Skillet-Classic: ScanQueuedReagents()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: AddToQueue({table})
Skillet-Classic: AdjustInventory()
Skillet-Classic: ScanQueuedReagents()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: queueAppendReagent(15417, 14, true), name= Devilsaur Leather
Skillet-Classic: queueAppendReagent(15407, 1, true), name= Cured Rugged Hide
Skillet-Classic: queueAppendReagent(14341, 1, true), name= Rune Thread
Skillet-Classic: AddToQueue({table})
Skillet-Classic: AdjustInventory()
Skillet-Classic: ScanQueuedReagents()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: PrintQueue(nil)
qpos= 1, command= {table}
qpos= 2, command= {table}
qpos= 3, command= {table}
qpos= 4, command= {table}
qpos= 5, command= {table}
qpos= 6, command= {table}

**Comment by b-morgan** [comment]
Opps, forgot a command. Type "/skillet tabledump on". For now, that's not needed because...

(Slaps self on forehead...) Leatherworking! Since you don't have any Rugged Leather, Skillet-Classic is trying to make some. Since you don't have any lower level leathers either, Skillet-Classic is trying to make them too. Bottom line, you need a crap load of Ruined Leather Scraps. Or...

You know those clicks that don't work in the recipe list? This is one reason why... Go to the Leather section of Leatherworking and right click "Rugged Leather", in the dialog, scroll down to "Ignore", mouseover the triangle and left click "Add Recipe to Ignored List". The screenshot below shows this process. I did the same thing on the other leathers and clicking the "Ignored List" button brings up that list (you can right click an item in the Ignored List to remove it).

Now click "Clear", go to your Devilsaur Leggings recipe and click "Queue" to create one. Shopping List should now make sense. If you had enough Rugged Leather in your possession (or enough of any other lower level leathers), Skillet-Classic would have used those instead of trying to craft them. Alternatively, you can uncheck the Skillet-Classic option "Queue Craftable Reagents".

![Leatherworking](https://user-images.githubusercontent.com/1547854/120104179-73b7e080-c110-11eb-9897-5a1d60727afe.jpg)

Let me know if you need screenshots of these other options.

**Comment by fireboy92k** [comment]
Ha.  Didn't even think about the fact that it would recurse that far into the recipe list to figure out how to make something.  My mind was on it only going like one level lower since I'm on a server with a fairly healthy economy thankfully, so usually getting a main component isn't a major issue.  And your right, who's going to grind out 15000 scraps?  LOL

One thing I DID notice is that when that's queued up, the number for craftable shows a 'huge' negative number vs just a simple '0' for you don't have anything to craft this.  But that seems like a minor thing now.

So okay, I think I'm good here as well.  Same as the other ones, sorry for all the back and forth and thanks for the help!

**Comment by b-morgan** [comment]
The negative numbers come into play when you own only some of the required materials and you are queuing multiple items that use the same materials. When you process the items in the queue, the negative numbers should return to zero.

**Comment by fireboy92k** [comment]
Thanks. I use the addon all the time, just apparently nowhere close to its potential.  LOL  I find the Blizz UI to be super hard to find things, etc.   I haven't played retail in years, so no idea if they made it any better there.

Thanks for keeping it going!
