### ISSUE TITLE
Materials list not updating

### ISSUE THREAD

**Issue by forlorvan** [b-morgan/Skillet-Classic#130]
![image](https://user-images.githubusercontent.com/98499612/205531850-16189970-3377-4573-acf2-206ff9809051.png)

The materials that is showing in the addon is not actual quantities in game. I have reset the saved variables several times, but does not get updated once reset.

There is also another issue I've noticed is that the recipes don't update correctly. After adding a new recipe the list will show the new recipe name, but link to what was in that position previously.

These issues may be related.

**Comment by b-morgan** [comment]
Please add the following line after line 1206 (`	Skillet:CalculateCraftableCounts()`) in `...\Addons\Skillet-Classic\SkilletData.lua`.

`	Skillet:SortAndFilterRecipes()`

and let me know if it fixes both issues. If you don't want to edit the code, I'll get a fixed version out later today.

**Comment by forlorvan** [comment]
I haven't been able to test extensively, but that fix is working.

**Comment by b-morgan** [comment]
That line was inadvertently removed between 1.56 and 1.57 so I'm pretty sure that will restore things to their former glory in 1.58.
