### ISSUE TITLE
LFG/Skillet Error

### ISSUE THREAD

**Issue by WorkPixels** [b-morgan/Skillet-Classic#131]
I'm getting this error anytime I queue into LFG tool. I have to reload before I can see who else is in LFG.

WoW WotLK
3.4.0.47168

25x [ADDON_ACTION_BLOCKED] AddOn 'Skillet-Classic' tried to call the protected function 'Search()'.
[string "@Interface\AddOns\!BugGrabber\BugGrabber.lua"]:480: in function <Interface\AddOns\!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `Search'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:225: in function `LFGBrowse_DoSearch'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:178: in function `SearchActiveEntry'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua"]:67: in function <...s\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:49>

**Comment by b-morgan** [comment]
Skillet-Classic has nothing to do with LFG and there are no calls to 'Search()' in the Skillet-Classic sources. This was also reported in #115 and as I said in that issue, there's not much I can do about it. It may have something to do with the ACE libraries.

If you disable all of your addons except Skillet-Classic does the problem still occur? If it does, please give me a set of steps to follow so I can see if I can reproduce it. If not, then you will have to reenable your addons in an organized manner until you find the actual culprit. 

I'd suggest using a "binary search", i.e. disable half your addons and test, if it fails disable half of those and try again. If it doesn't fail, enable half of the rest and try again, etc.

**Comment by WorkPixels** [comment]
Okay, I'll try to do some troubleshooting. Thank you for letting me know.

**Comment by WorkPixels** [comment]
Yeah, it's weird. The error only seems to go away when I have Skillet disabled.

**Comment by b-morgan** [comment]
OK. Give me instructions on how to reproduce the error with just Skillet-Classic enabled. If I can reproduce then maybe I can do something.

**Comment by WorkPixels** [comment]
Alright, with Skillet enabled. All I do is go into the LFG tool in WoW WotLK. Select a few dungeons to run. As soon as I hit the "List Self" button I get the error I posted. I then have to reload my UI to be able to see who else is LFG.

**Comment by b-morgan** [comment]
Is Skillet-Classic the only addon you have enabled? I did exactly the same thing and it worked for me.

**Comment by WorkPixels** [comment]
I deleted the LUA file and addon folder. Re-installed and it seems to might have fixed it.

**Comment by b-morgan** [comment]
OK. Feel free to reopen this or open a new issue if the problem returns and can be reproduced.
