### ISSUE TITLE
Unable to open trade skills window after phase 2 update

### ISSUE THREAD

**Issue by Brodieman** [b-morgan/Skillet-Classic#132]
Logged in today and I am unable to open ay trade skills windows with Skillet enabled.  Nothing happens

**Comment by b-morgan** [comment]
I'm working on it! Should have a release out later today.

**Comment by Brodieman** [comment]
I figured, just thought I thought drop a note!

**Comment by b-morgan** [comment]
Skillet-Classic-1.59-alpha1 should work. I'll release Skillet-Classic-1.59 very quickly as soon as I verify the build and that I didn't break Classic Era.

**Comment by Brodieman** [comment]
No rush, thanks!

**Comment by b-morgan** [comment]
[Skillet-Classic-1.59](https://www.curseforge.com/wow/addons/skillet-classic/files/4351753) has been released.
