### ISSUE TITLE
1.59 broken

### ISSUE THREAD

**Issue by Velarax** [b-morgan/Skillet-Classic#134]
The latest version does not work.  Clicking a skill window opens inventory bags, but not skills.

**Comment by b-morgan** [comment]
Skillet-Classic-1.60 has been released but CurseForge hasn't approved it yet. 

It is available at [https://www.wowinterface.com/downloads/info25287-Skillet-Classic.html](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.wowinterface.com%252fdownloads%252finfo25287-Skillet-Classic.html) or https://github.com/b-morgan/Skillet-Classic/releases/tag/1.60.

Please try with that version and let me know.

**Comment by Velarax** [comment]
You are a god!  I found the conflict with 1.59 was mstl however 1.6 fixes all.  Big applause!
