### ISSUE TITLE
Unknown event "BAG_CONTAINER_UPDATE" in Classic Era

### ISSUE THREAD

**Issue by brykrys** [b-morgan/Skillet-Classic#138]
Version 1.61-classic (TOC interface version 11403)

I received the below error at login, and tracked the source to Skillet attempting to register event "BAG_CONTAINER_UPDATE", which I believe is new in 3.4.1 but does not exist in 1.14.3.

Date: 2023-01-20 12:28:17
ID: -1
Error occured in: Global
Count: 1
Message: ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua line 33:
   Attempt to register unknown event "BAG_CONTAINER_UPDATE"
Debug:
   [string "=[C]"]: RegisterEvent()
   [string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:33: OnUsed()
   [string "@LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua"]:132: RegisterEvent()
   [string "@Skillet-Classic\Skillet.lua"]:694:
      Skillet-Classic\Skillet.lua:673
   [string "=[C]"]: ?
   [string "@!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:66:
      ...s\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:61
   [string "@!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:523: EnableAddon()
   [string "@!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:626:
      ...s\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:611
Locals:
None
AddOns:
  KalielsTracker, v1.4.2
  nLog, v<%version%> (<%codename%>)
  Swatter, v<%version%> (<%codename%>)
  AdvancedInterfaceOptions, v1.8.4
  Altoholic, v1.14.003
  AucAdvanced, v<%version%> (<%codename%>)
  AucFilterBasic, v<%version%> (<%codename%>)
  AucFilterFlatOutlier, v<%version%> (<%codename%>)
  AucFilterOutlier, v<%version%> (<%codename%>)
  AucMatchUndercut, v<%version%> (<%codename%>)
  AucStatDebug, v<%version%> (<%codename%>)
  AucStatHistogram, v<%version%> (<%codename%>)
  AucStatiLevel, v<%version%> (<%codename%>)
  AucStatPurchased, v<%version%> (<%codename%>)
  AucStatSales, v<%version%> (<%codename%>)
  AucStatSimple, v<%version%> (<%codename%>)
  AucStatStdDev, v<%version%> (<%codename%>)
  AucStatWOWEcon, v<%version%> (<%codename%>)
  AucUtilAHWindowControl, v<%version%> (<%codename%>)
  AucUtilAppraiser, v<%version%> (<%codename%>)
  AucUtilAskPrice, v<%version%> (<%codename%>)
  AucUtilAutoMagic, v9.1.DEV.5415
  AucUtilCompactUI, v<%version%> (<%codename%>)
  AucUtilEasyBuyout, v<%version%> (<%codename%>)
  AucUtilFixAH, v<%version%> (<%codename%>)
  AucUtilItemSuggest, v<%version%> (<%codename%>)
  AucUtilMatsTaper, v1.2
  AucUtilPriceLevel, v<%version%> (<%codename%>)
  AucUtilScanButton, v<%version%> (<%codename%>)
  AucUtilScanFinish, v<%version%> (<%codename%>)
  AucUtilScanProgress, v<%version%> (<%codename%>)
  AucUtilScanStart, v<%version%> (<%codename%>)
  AucUtilSearchUI, v<%version%> (<%codename%>)
  AucUtilSimpleAuction, v<%version%> (<%codename%>)
  AucUtilVendMarkup, v<%version%> (<%codename%>)
  Babylonian, v<%version%> (<%codename%>)
  BeanCounter, v<%version%> (<%codename%>)
  ChatClear, v1.13
  ClassicAuraDurations, v3.0
  Configator, v<%version%> (<%codename%>)
  DataStore, v2022.06.05
  DataStoreAgenda, v1.14.003
  DataStoreAuctions, v1.14.003
  DataStoreCharacters, v2022.06.05
  DataStoreContainers, v1.14.003
  DataStoreCrafts, v1.14.003
  DataStoreInventory, v1.14.003
  DataStoreMails, v2022.06.05
  DataStoreQuests, v1.14.003
  DataStoreReputations, v1.14.003
  DataStoreSpells, v2022.06.05
  DataStoreTalents, v1.14.003
  DebugLib, v<%version%> (<%codename%>)
  DefaultAnchor, v1.24
  Dominos, v10.0.15
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v5.1.DEV.4632
  EnchantrixBarker, v<%version%> (<%codename%>)
  FishingBuddy, v0.8.4
  FixSettings, v1.1
  HandyNotes, vv1.6.13
  IceHUD, vv1.14.11
  LibDataBroker, v
  LibExtraTip, v<%version%> (<%codename%>)
  LinkWrangler, v2.07
  LinkWranglerAuctioneer, v1.70
  LiteButtonAuras, v10.0.14
  LoseControl, v1.17
  Mapster, v1.10.4
  OmniCC, v10.0.2
  Outfitter, v1.3.0
  Pawn, v2.7.15
  Postal, vv3.9.2
  SkilletClassic, v1.61
  SlideBar, v<%version%> (<%codename%>)
  Stubby, v<%version%> (<%codename%>)
  TipHelper, v<%version%> (<%codename%>)
  TitanClassic, v1.3.1.11401
  TitanClassicAmmo, v1.3.1.11401
  TitanClassicBag, v1.3.1.11401
  TitanClassicClock, v1.3.1.11401
  TitanClassicGold, v1.3.1.11401
  TitanClassicLocation, v1.3.1.11401
  TitanClassicLootType, v1.3.1.11401
  TitanClassicPerformance, v1.3.1.11401
  TitanClassicRegen, v1.3.1.11401
  TitanClassicRepair, v1.3.1.11401
  TitanClassicXP, v1.3.1.11401
  TooltipItemIcon, v1.81
  tullaRange, v10.0.9
  WeakAuras, v5.3.5
  BlizRuntimeLib_enUS v1.14.3.11403 <none>
  (ck=cd0)

**Comment by b-morgan** [comment]
Fixed in the next release. You can comment out line 694 in `...\Addons\Skillet-Classic\Skillet.lua`.
