### ISSUE TITLE
Item icons are 'flipping in the regent list as you hover over them

### ISSUE THREAD

**Issue by fireboy92k** [b-morgan/Skillet-Classic#14]
This is confirmed with only Skillet loaded, so not another addon messing with things.

In the normal view with no mouse over the regent/item icons are correct.  See picture:
![image](https://user-images.githubusercontent.com/56378639/120088366-953bac80-c0bd-11eb-8e65-140294e34f72.png)

When you hover over a regent or item however, the icon shifts to something else.  Everything else stays correct including the tool tip.  In following image for same item from the previous image notice that the leather icon has changed to a 'gear'.  This only happens with some items and not all.

![image](https://user-images.githubusercontent.com/56378639/120088379-cc11c280-c0bd-11eb-8ff1-2c85e0688a75.png)

**Comment by b-morgan** [comment]
What happens if you click on a reagent that has the gear icon?

**Comment by b-morgan** [comment]
Maybe I shouldn't spoil the fun but I'm guessing your professions are Engineering and Leatherworking.

The icon change indicates that the item is craftable by you and clicking on it will take you to that recipe (and add an icon next to the "Ignored List" button which, when clicked, will take you back. Click on the Green Tinted goggles in the recipe above and then click on the leather item in that one. You should now be two levels deep and you can click on the "back" icon twice to return to "Fire Goggles".

**Comment by fireboy92k** [comment]
I have more than one character, so was swapping back and forth.  

If that's the way it supposed to work so be be it and good to know!  Sorry for all the extra work on your part for my posts.
