### ISSUE TITLE
shopping error with latest wrath release

### ISSUE THREAD

**Issue by MyTechnoHunter** [b-morgan/Skillet-Classic#141]
1x Skillet-Classic/UI/ShoppingList.lua:472: attempt to index field '?' (a nil value)
[string "@Skillet-Classic/UI/ShoppingList.lua"]:472: in function <Skillet-Classic/UI/ShoppingList.lua:441>
[string "@Skillet-Classic/UI/ShoppingList.lua"]:485: in function `?'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
tab = 1
guildName = "Natural Born Grillers"
cachedGuildbank = <table> {
}
name = "Consumables"
icon = 135999
isViewable = true
canDeposit = true
numWithdrawals = 1
remainingWithdrawals = 1
(for index) = 1
(for limit) = 98
(for step) = 1
slot = 1
item = "|cffffffff|Hitem:46377::::::::24:::::::::|h[Flask of Endless Rage]|h|r"
_ = 236880
count = 3
id = 46377
(*temporary) = nil
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = <table> {
 id = 46377
 bag = 1
 count = 3
 slot = 1
}
(*temporary) = "attempt to index field '?' (a nil value)"
DA = <table> {
 DeleteIgnoreEntry = <function> defined @Skillet-Classic/UI/IgnoreList.lua:170
 VendorItemAvailable = <function> defined @Skillet-Classic/Inventory.lua:251
 SkillButton_NewGroup = <function> defined @Skillet-Classic/UI/MainFrame.lua:2328
 modules = <table> {
 }
 ClearQueue = <function> defined @Skillet-Classic/SkilletQueue.lua:268
 RecipeGroupInitFlatten = <function> defined @Skillet-Classic/RecipeGroups.lua:436
 MERCHANT_UPDATE = <function> defined @Skillet-Classic/UI/MerchantWindow.lua:209
 SkilletShow = <function> defined @Skillet-Classic/Skillet.lua:1158
 DisplayShoppingList = <function> defined @Skillet-Classic/UI/ShoppingList.lua:1298
 ShowQueueView = <function> defined @Skillet-Classic/UI/MainFrame.lua:3360
 TRADE_POTENTIAL_BIND_ENCHANT = <function> defined @Skillet-Classic/Skillet.lua:1319
 SKILL_LINES_CHANGED = <function> defined @Skillet-Classic/Skillet.lua:959
 ScheduleTimer = <function> defined @Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 FilterDropDown_OnShow = <function> defined @Skillet-Classic/UI/Filtering.lua:81
 hideTrivialRecipes = false
 RecipeGroupSort = <function> defined @Skillet-Classic/RecipeGroups.lua:410
 EnableResize = <function> defined @Skillet-Classic/UI/Utils.lua:129
 EnchantSpellToItem = <table> {
 }
 db = <table> {
 }
 bankBusy = false
 UpdateNotesWindow = <function> defined @Skillet-Classic/UI/RecipeNotes.lua:123
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 SkilletShowWindow = <function> defined @Skillet-Classic/Skillet.lua:1235
 AdditionalButtonsList = <table> {
 }
 CHAT = <function> defined @Skillet-Classic/DebugAids.lua:83
 IgnoreList_OnScroll = <function> defined @Skillet-Classic/UI/IgnoreList.lua:290
 SortDropdown_OnLoad = <function> defined @Skillet-Classic/UI/Sorting.lua:551
 pluginsOptions = <table> {
 }
 UnregisterAllEvents = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 RecipeGroupFlatten = <function> defined @Skillet-Classic/RecipeGroups.lua:457
 RecipeGroupMoveEntry = <function> defined @Skillet-Classic/RecipeGroups.lua:291
 EnablePauseButton = <function> defined @Skillet-Classic/UI/MainFrame.lua:202
 ReagentButtonSkillSelect = <function> defined @Skillet-Classic/UI/MainFrame.lua:2638
 ShowReagentDetails = <function> defined @Skillet-Classic/UI/MainFrame.lua:3251
 GetTradeSkillTools = <function> defined @Skillet-Classic/TradeskillInfo.lua:237
 bopCheck = <function> defined @Skillet-Classic/UI/MainFrame.lua:1711
 RecipeGroupClearEntries = <function> defined @Skillet-Classic/RecipeGroups.lua:128
 SkillExpandButton_OnClick = <function> defined @Skillet-Classic/UI/MainFrame.lua:2452
 TABLE = <function> defined @Skillet-Classic/DebugAids.lua:352
 FixBugs = true
 Unhook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:417
 InventoryFilterButton_OnShow = <function> defined @Skillet-Classic/UI/MainFrame.lua:2898
 SetTradeSkillToolTip = <function> defined @Skillet-Classic/UI/MainFrame

**Comment by b-morgan** [comment]
Is this repeatable? How soon after starting the session did this error occur? Was this character in the guild prior to logging on?

The table referenced on line 472 should have been initialized earlier but replace `...\Addons\Skillet-Classic\UI\ShoppingList.lua with the one in this zip file which will initialized it again.

[ShoppingList.zip](https://github.com/b-morgan/Skillet-Classic/files/10886154/ShoppingList.zip)

**Comment by MyTechnoHunter** [comment]
will test, do you want me to replace the file then test or test first?

**Comment by b-morgan** [comment]
I suspect that it is not repeatable but if you can verify that I'd appreciate it. You could also just replace the file and verify that this error goes away (and no new errors appear 😄 ).

**Comment by MyTechnoHunter** [comment]
Will do
