### ISSUE TITLE
[Request][Skillet Classic][WOTLk]  Is it possible to overwrite material cost?

### ISSUE THREAD

**Issue by Raithen88** [b-morgan/Skillet-Classic#142]
Hi,
I was wondering if it is possible to overwrite the cost of certain materials. For example, one Abyss Crystal costs ~80g on my server, but with certain methods, it is possible for me to lower the cost (through tailoring) to ~55g per Crystal.
Since Skillet uses the Database from Auctionator to calculate profits, some recipes are now at a higher cost then the real calculation should be.

For example:
Berserk uses 10 Abys Crytals. Skillet now says, 10 x 80g = 800 for the Abys Crystals, which is true, if it's calculation is based on the Auctionhouse values. Since I can lower this price down to 10 x 55 = 550g, the real profit is much higher then the calculation in skillet shows.

To fullfill this request, I think, there has to be alot of work done. Let us hear, if it is possible nontheless.

Best Regards
Raithen

**Comment by b-morgan** [comment]
I don't think this is an appropriate addition to Skillet-Classic. As you point out, a lot of work. Does TradeSkillMaster do something like this? 

While it wouldn't be hard to add some code to the Auctionator plugin to fetch the AH cost, compare it to some table of costs and use the lower value. The code (and UI) to maintain that table doesn't exist and I'm not interested in developing it. Something that might be possible (in the Auctionator plugin) would be to subtract from the cost materials already on hand. So in your example, if you have 5 crystals in your inventory, just use 5 x 80g in the cost calculation.

**Comment by Raithen88** [comment]
I'm in contact with someone who uses TSM. Unfortunately, it is only possible to use "craft"-costs, based on base items.
What I would need is:
- A new database. Via "add", you could add an Item, for example an abyss crystal.
- Add custom prices to the items in the database
- A true/false flag for "use custom prices for the materials in the database"

Then the calculation of the profit should use the custom prices of the new table to calculate the profit.

Yes, it's a lot of work. But it was a spontanous idea :)

**Comment by b-morgan** [comment]
The Auctionator plugin could handle the calculations and an option to turn it on or off. The hard part is maintaining the database. If you can find an addon that lets you build and maintain a custom table, then it might be possible to implement this request.

**Comment by b-morgan** [comment]
Approximately how many items and how often would you change the prices on those items?

**Comment by b-morgan** [comment]
[Skillet-Classic-1.68-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/4491412) implements this request by adding a customPrice table (used by the Auctionator plugin) and managed with the following commands:

`/skillet customshow` will show the current contents of the customPrice table. This is currently a global table and is saved in the global saved variables file.
`/skillet customclear` will empty the table.
`/skillet customadd id,price` will add an item to the table with a price (in copper, 10000 = 1g).
`/skillet customadd link,price` will extract the id from the link and add it to the table.
`/skillet customdel id` will remove an item from the table.
`/skillet customdel link` will extract the id from the link and remove it from the table.

Note that '/skillet customadd' will overwrite an existing entry (i.e. update the price). The `link` for an item can be generated by shift-clicking the reagent in the Skillet-Classic detail frame.

The Auctionator plugin has a new option, customPrice, which will enable substituting the price from the customPrice table for the Auctionator price of the reagent. This substitution only occurs if the price from the customPrice table is less than the Auctionator price. When a substitution is successful, an orange "*" is appended to the reagent name in the cost section of the Skillet-Classic detail frame.

A future version may implement a GUI to manage the customPrice table but this is not guaranteed.
