### ISSUE TITLE
The search/filter feature doesn't work properly

### ISSUE THREAD

**Issue by fnx521** [b-morgan/Skillet-Classic#145]
'ello! The search/filter feature stopped working some months ago. Here is an example of working (Skillet-Classic-1.45-classic) vs not working (Skillet-Classic-1.68-classic) versions. Classic Era, affects every profession as far as I can tell. Would like to see this fixed, please. Thank you for the awesome job on the addon!
![image](https://user-images.githubusercontent.com/1431948/236011583-7278b7a3-3a9f-46da-a2b1-6d2345b0b512.png)
![image](https://user-images.githubusercontent.com/1431948/236011670-d17a80b1-cdcb-4d49-be2f-3a0f296995ee.png)

**Comment by b-morgan** [comment]
[Skillet-Classic-1.47](https://legacy.curseforge.com/wow/addons/skillet-classic/files/3958603) works and [Skillet-Classic-1.48](https://legacy.curseforge.com/wow/addons/skillet-classic/files/3974153) fails. Investigating...

**Comment by b-morgan** [comment]
Install [Skillet-Classic-1.68-classic](https://legacy.curseforge.com/wow/addons/skillet-classic/files/4519839) and replace the file `...\Addons\Skillet-Classic\SkilletData.lua` with the one in the attached zip file and let me know if that works better.
[SkilletData.zip](https://github.com/b-morgan/Skillet-Classic/files/11391445/SkilletData.zip)

**Comment by fnx521** [comment]
Yes, it works perfectly this way.

**Comment by TheHeikster** [comment]
Replacing the file fixed it for me as well. Thanks!

**Comment by b-morgan** [comment]
[Skillet-Classic-1.69-classic](https://legacy.curseforge.com/wow/addons/skillet-classic/files/4521561) contains this fix.
