### ISSUE TITLE
Filter sorting

### ISSUE THREAD

**Issue by Gunner-web** [b-morgan/Skillet-Classic#147]
In Enchanting, I can't use the Filter option but I can in Tailoring.  Is it supposed to be that way?
![WoWScrnShot_050623_190058](https://user-images.githubusercontent.com/88938346/236651245-d3f7405d-89d6-46ad-9db5-23eb7dcd63be.jpg)

![WoWScrnShot_050623_190808](https://user-images.githubusercontent.com/88938346/236651262-3f12a11b-5d67-429d-80d6-173a6129dd31.jpg)

**Comment by b-morgan** [comment]
The Filter SubClass and InvSlot dropdown groups are populated by the itemSubType and itemEquipLoc values returned from the Blizzard API function GetItemInfo. In Classic Era, enchants don't create items so there is nothing to pass to GetItemInfo and therefore, no return values (there are a couple of enchant recipes that do create items but the Blizzard API in Classic Era doesn't provide enough information to do anything).
