### ISSUE TITLE
Wrath 3.4.2 - Scrolling doesn't work

### ISSUE THREAD

**Issue by NayooZ** [b-morgan/Skillet-Classic#149]
Skillet Classic v1.72
Wow Classic: 3.4.2.50063

Just updated to the new wrath patch and skillet no longer scrolls. The scrollbar moves and can be dragged but the recipe list does not move.

**Comment by b-morgan** [comment]
Fixed in [Skillet-Classic-1.73-wrath](https://legacy.curseforge.com/wow/addons/skillet-classic/files/4599457)
