### ISSUE TITLE
Shopping list not working properly with new update ?

### ISSUE THREAD

**Issue by Anakia69** [b-morgan/Skillet-Classic#150]
Hello there, 

It seems that the purchase list is not working properly with the new update. 

I have to buy a component so that it automatically buys the reagents that are queued in my process list. If I don't force it, the "Buy Reagents" button isn't there and the automatic purchase does not work either.

Maybe it's only on my side?

**Comment by b-morgan** [comment]
It's not me, it's not you, it's them...

This should be fixed in[ Skillet-Classic-1.74-alpha1](https://legacy.curseforge.com/wow/addons/skillet-classic/files/4605752).
