### ISSUE TITLE
Link needed material to current opened chat

### ISSUE THREAD

**Issue by whtmst** [b-morgan/Skillet-Classic#157]
Hello. Thank you for responding to me on CurseForge. As you requested, I have created a topic on GitHub.

The idea is as follows: as you can see in the video, would be super nice to see a feature in your addon where, when holding down the Shift key and clicking the left mouse button on craft item, in the open chat, the ingredients for the craft item would be linked. This would be very convenient when you are asked multiple times a day about the materials and quantities needed to craft certain gloves or a chest or other thinks.

Video: https://youtu.be/rwN2JNUjGDI

This is done in this addon (https://github.com/laytya/AdvancedTradeSkillWindow-vanilla) but unfortunately it does not work on the official version of WoW Classic.

And I also wanted to ask if it is possible to somehow make an ElvUI skin so that the addon looks more organic if you use it together with ElvUI.

**Comment by b-morgan** [comment]
In the Skillet-Classic details (right side) frame, shift-click the icon will send the recipe name to chat and alt-click will send the reagent list to chat. If the reagent is craftable, an asterisk is appended. 

When I get the code working, ctrl-alt-click will send the expanded (i.e. only basic) reagent list to chat.

I have never used ElvUI so I have no idea how to do a skin. If you want to develop a skin for Skillet-Classic, I will consider making it available to others.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.81-alpha1](https://legacy.curseforge.com/wow/addons/skillet-classic/files) contains the ctrl-alt-click code. It is still a work in progress as there are some recipes (mostly Engineering) that fail. If you find a recipe that fails, please add a comment to this ticket with the profession, recipe, output and the expected output. If Skillet-Classic gets a lua error, please add that as well.

**Comment by whtmst** [comment]
> In the Skillet-Classic details (right side) frame, shift-click the icon will send the recipe name to chat and alt-click will send the reagent list to chat. If the reagent is craftable, an asterisk is appended.

Thx, it's work. In my opinion u must write this tooltip in addon, so player can know about link.

**Comment by whtmst** [comment]
> [Skillet-Classic-1.81-alpha2](https://legacy.curseforge.com/wow/addons/skillet-classic/files) contains the ctrl-alt-click code. It is still a work in progress as there are some recipes (mostly Engineering) that fail. If you find a recipe that fails, please add a comment to this ticket with the profession, recipe, output and the expected output. If Skillet-Classic gets a lua error, please add that as well.

Thank you very much. I'll wait for the stable version in CurseForge from u. And about recipes or other errors, I will definitely let you know.

**Comment by b-morgan** [comment]
The stable version could be a long time coming. 

If you are using the CurseForge app, you can switch to alphas and install the latest and then switch back to stable if it fails miserably.

**Comment by b-morgan** [comment]
Skillet-Classic-1.81 contains code to link the item produced, link the recipe reagents, and link the basic reagents.
