### ISSUE TITLE
Blank skills window all professions SOD

### ISSUE THREAD

**Issue by Velarax** [b-morgan/Skillet-Classic#160]
Skillet window opens but is blank.  No recipes, no ingredients, nothing. Using latest Classic version.

**Comment by b-morgan** [comment]
I suspect that your installation of Skillet-Classic is corrupt. Please [download 1.80](https://legacy.curseforge.com/wow/addons/skillet-classic/files) again. You may need to download it manually and [check the MD5 sum](https://portal.nutanix.com/page/documents/kbs/details?targetId=kA07V000000LWYqSAO).

If that doesn't fix it, you may have a conflicting addon (that I am unaware of). If this is the case, please let me know what addon it is so I can attempt to discover how to prevent this from happening to someone else. If you need help finding the culprit, let me know.

Last possibility would be a corrupt global saved variables file, Skillet-Classic.lua, which is found in the WTF folder. Let me know if you need help finding it.

**Comment by b-morgan** [comment]
Please open a new issue if this isn't fixed.

**Comment by Velarax** [comment]
Brad it looks like the last update fixed it, although I am at this point not really convinced it was Skillet... I think it was MTSW

**Comment by b-morgan** [comment]
MTSW is, unfortunately, almost abandoned. While its database is probably good for SoD, Blizzard's changes to the API haven't been applied.

**Comment by Velarax** [comment]
I know... and apparently some nice soul updated it so both it and Skillet once again work together in harmony.  Thank you again for your tireless efforts.  They are much appreciated.
