### ISSUE TITLE
Wrong Skill Data for Undermine Clam Chowder

### ISSUE THREAD

**Issue by TrusterX** [b-morgan/Skillet-Classic#161]
It looks like the Skillet Data for Undermine Clam Chowder are inconsistent. While it shows
225/250/262/275
(orange/yellow/green/grey), 

i'm on 275 and it's still yellow on classic (hc):

![WoWScrnShot_021224_212959-2](https://github.com/b-morgan/Skillet-Classic/assets/6065454/3b02924b-3cb1-4f2f-b246-b3cd7dc1f217)

the same also for Tender Wolf Steak

**Comment by b-morgan** [comment]
This data is not something that can be obtained from the Blizzard API. There are various sources including other addons. Skillet-Classic has its own table contained in `SkillLevelData.lua` which was initially populated by a user scraping the data from Wowhead. I have provided their scraper code in `ScrapeWowhead.js`. I do not run the scraper (I've had limited success in doing so) on a regular basis.

I'll make the adjustments to the SkillLevelData.lua file for these two cases but if someone runs the scraper (hint, hint) and provides an updated SkillLevelData.lua file, I'll include that in the next release.

https://www.wowhead.com/classic/spell=20626/undermine-clam-chowder

https://www.wowhead.com/classic/spell=22480/tender-wolf-steak

Note:
```
-- InitializeSkillLevels is only called if the table does not exist.
-- Force refresh with '/skillet initskilllevels'
-- or '/run Skillet:InitializeSkillLevels()'
-- or '/run Skillet.db.global.SkillLevels = nil'
```

**Comment by b-morgan** [comment]
With some help I was able to scrape Wowhead and update the skill level data for all WotLK professions.

[Skillet-Classic-1.83-alpha1](https://legacy.curseforge.com/wow/addons/skillet-classic/files/5128836) contains the updated data but unfortunately, I believe the data for these two recipes is still wrong.

I'm looking at finding a different source for the data and I'll post progress here when there is some.

**Comment by b-morgan** [comment]
Skillet-Classic-1.86-classic (and Skillet-Classic-1.86-cata) has some experimental code included which may solve this issue. The alternate source uses tables from [Wago Tools](https://wago.tools/), one for "Classic Era" and one for "Classic Cataclysm". The addon [CraftInfoAnywhere](https://www.curseforge.com/wow/addons/craft-info-anywhere) is needed for this code to function along with some (undocumented) chat commands to enable / disable it.

The chat command `/skillet altskilllevels` will toggle the use of the alternate source for "yellow/green/grey" and `/skillet baseskilllevel` will toggle using the alternate source for the "orange" level.

The Wago Tools table(s) do not contain the data needed to determine the transition from red to orange (i.e. the skill level minimum for learning / using a recipe) for most of the recipes. Except for the "look" of the bar graph this should have no effect on any other calculations.

I don't have characters with a high enough skill level to test your example recipe so I will need your feedback to determine if this actually solves this issue. I would like to abandon the Wowhead tables in the future so I'd also like your feedback on the changed look of the bar graph.

There are some debug statements in the code that can be enabled with `/skillet debugshow` and `/skillet debuglevel 2`. Another `/skillet debugshow` will turn off the chat spam.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.88-classic](https://legacy.curseforge.com/wow/addons/skillet-classic/files/5320852) has removed the `/skillet altskilllevels` switch and uses a blend of the Wago Tools (if CraftInfoAnywhere is installed) and Wowhead data. The `/skillet baseskilllevel` still toggles the use of the Wago Tools "orange" level.
