### ISSUE TITLE
Wrong queue item appears in processing list

### ISSUE THREAD

**Issue by luckytomes** [b-morgan/Skillet-Classic#162]
I have two professions; Enchant and Alchemy. When I queue for Elixir of Water Breathing, which uses Blackmouth Oil x2, Stranglekelp x1, and Empty Vial x2, with the mats for Blackmouth Oil but not made yet, it queues this: 
2x Enchanting: Enchant Bracer Minor Deflect (instead of 2x Blackmouth Oil)
1x Alchemy: Elixir of Water Breathing (this is correct)

Thanks! -Lucky
![SkilletSS](https://github.com/b-morgan/Skillet-Classic/assets/160536326/0386cce1-dd7e-4281-b31b-40e8b07d8d3e)

**Comment by b-morgan** [comment]
I'm going to guess that Skillet-Classic's database has become corrupted somehow. Please upload a zip of your global saved variables file, Skillet-Classic.lua. Try typing `/skillet flushrecipedata` and `/skillet flushplayerdata` and try again. If it still fails, then we will need to enable debugging and see if I can figure out what is wrong.

I see you have items in the ignore list. Can you show or tell me what items are in the list?

I checked my Alchemist/Herbalist and Skillet-Classic does the right thing for this recipe so hopefully, resetting the database will fix yours as well.

**Comment by luckytomes** [comment]
-- [Skillet-Classic.zip](https://github.com/b-morgan/Skillet-Classic/files/14337219/Skillet-Classic.zip)
-- The items on ignore are just the enchanting rods (Copper Runed Rod, Silver Runed Rod, Gold Runed Rod).
-- I entered the /skillet commands as suggested above and tried again, which worked. Thanks :)
![SkilletSS2](https://github.com/b-morgan/Skillet-Classic/assets/160536326/83caaac0-961c-4a97-af56-b585c97808ad)

**Comment by luckytomes** [comment]
[Skillet-Classic Post purge lua.zip](https://github.com/b-morgan/Skillet-Classic/files/14337300/Skillet-Classic.Post.purge.lua.zip)
Here is the .lua zip after the purging, for comparison. Thanks again!
