### ISSUE TITLE
issue with search using filter

### ISSUE THREAD

**Issue by miguelguerreiro1980** [b-morgan/Skillet-Classic#166]
when I search for an item, it works:
<img width="505" alt="ok" src="https://github.com/b-morgan/Skillet-Classic/assets/8236969/c5c30ba7-3d02-4565-934d-bcc702faf707">

but same search, but filtering by "chest":
<img width="504" alt="nok" src="https://github.com/b-morgan/Skillet-Classic/assets/8236969/9c4da61c-9594-4abc-b8fa-7e03af61450f">

**Comment by b-morgan** [comment]
I had a similar failure yesterday but after enabling debugging and uncommenting some debug statements, it is not failing today. The case I used was Filter "Chest" and Search "dress".

Please replace `...\Addons\Skillet-Classic\UI\Filtering.lua` with 
[Filtering.zip](https://github.com/b-morgan/Skillet-Classic/files/14461620/Filtering.zip).

Type the following in chat, `/skillet debugshow`, `/skillet debuglevel 2`, `/skillet tabledump`. Open Skillet-Classic and recreate the issue. Exit WoW and attach a zip of your character specific saved variables file `Skillet-Classic.lua`

You can type `/skillet debugshow off` to stop the chat spam.

**Comment by miguelguerreiro1980** [comment]
Here you go. Thanks for the help 
[Skillet-Classic.lua.zip](https://github.com/b-morgan/Skillet-Classic/files/14462152/Skillet-Classic.lua.zip)

**Comment by b-morgan** [comment]
The reason why it fails is that INVTYPE_ROBE doesn't match INVTYPE_CHEST even though both go into the chest slot. More research is needed.

	"Fri Mar  1 14:09:33 2024(D1): RecipeFilter: itemID= 7054, subClass= Cloth, invSlot= INVTYPE_ROBE", -- [3728]
	"Fri Mar  1 14:09:33 2024(D1): RecipeFilter: subClass.selected= None, invSlot.selected= INVTYPE_CHEST", -- [3729]
	"Fri Mar  1 14:09:33 2024(D1): RecipeFilter: filtering active, Robe of Power did not meet the criteria", -- [3730]

**Comment by b-morgan** [comment]
[Skillet-Classic-alpha2](https://legacy.curseforge.com/wow/addons/skillet-classic/files/5151038) contains a fix for this issue. Please try it and let me know.

**Comment by miguelguerreiro1980** [comment]
this fixed the issue :) ty
