### ISSUE TITLE
Skillups are using WotLK values for SoD

### ISSUE THREAD

**Issue by zackeryps** [b-morgan/Skillet-Classic#167]
As an example, Nightfin soup starts at 250, turns yellow at 290, green at 310, and finally grey at 330.
However, the addon uses the skillup values that were changed for WotLK.
E.g. Nightfin soup starts at 250, turns yellow at 275, green at 285, and finally grey at 295.
This causes the calculation for %chance of a skillup to be incorrect.

**Comment by b-morgan** [comment]
Blizzard doesn't make these values available via the API. They are "reverse engineered" and/or "scraped" from places like Wowhead. This is a very labor intensive operation and is exasperated by having three different streams that need separate data for each.

I will take this issue under advisement but I'm not sure if a solution I can live with will be found anytime soon.

**Comment by b-morgan** [comment]
See #161 for additional information.

**Comment by b-morgan** [comment]
Skillet-Classic-1.86-classic (and Skillet-Classic-1.86-cata) has some experimental code included which may solve this issue. The alternate source uses tables from [Wago Tools](https://wago.tools/), one for "Classic Era" and one for "Classic Cataclysm". The addon [CraftInfoAnywhere](https://www.curseforge.com/wow/addons/craft-info-anywhere) is needed for this code to function along with some (undocumented) chat commands to enable / disable it.

The chat command `/skillet altskilllevels` will toggle the use of the alternate source for "yellow/green/grey" and `/skillet baseskilllevel` will toggle using the alternate source for the "orange" level.

The Wago Tools table(s) do not contain the data needed to determine the transition from red to orange (i.e. the skill level minimum for learning / using a recipe) for most of the recipes. Except for the "look" of the bar graph this should have no effect on any other calculations.

I don't have characters with a high enough skill level to test your example recipe so I will need your feedback to determine if this actually solves this issue. I would like to abandon the Wowhead tables in the future so I'd also like your feedback on the changed look of the bar graph.

There are some debug statements in the code that can be enabled with `/skillet debugshow` and `/skillet debuglevel 2`. Another `/skillet debugshow` will turn off the chat spam.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.88-classic](https://legacy.curseforge.com/wow/addons/skillet-classic/files/5320852) has removed the `/skillet altskilllevels` switch and uses a blend of the Wago Tools (if CraftInfoAnywhere is installed) and Wowhead data. The `/skillet baseskilllevel` still toggles the use of the Wago Tools "orange" level.

**Comment by zackeryps** [comment]
After updating, I noticed that it was still using the wotlk values when not using Craft Info Anywhere. However, the integration with CIA appears to function based on the recipes that I checked.

Thank you. I love this addon.

**Comment by b-morgan** [comment]
@zackeryps, The Wowhead data has not been (and probably will not be) updated. CraftInfoAnywhere is required to use the Wago Tools data which has separate values for Classic Era and Cataclysm. the baseskilllevel switch only effects where the "orange" value starts.

I may incorporate the CraftInfoAnywhere data in a later version of Skillet-Classic.
