### ISSUE TITLE
Sort by ATR: Buyout not reliable since pre-patch (Cata Classic)

### ISSUE THREAD

**Issue by Esc1972** [b-morgan/Skillet-Classic#169]
Hi,

Sorting profession window by ATR buyout is not quite working, i am focusing on inscription, the majority are sorting correctly in order but certain glyphs are not;

- Glyph of blessing of kings
- Glyph of silencing shot
- Gylph of revive pet
- Glyph of Vendetta
- Glyph of Shadowfiend
- Glyph of Psychic Scream

I am using Journalator data to drive this and have been throughout wrath classic not issues noted until now

Thanks!
Ian

**Comment by Esc1972** [comment]
Add:
- glyph of mutilate
- Glyph of maul

**Comment by b-morgan** [comment]
Unfortunately, "not quite working" doesn't help me find a bug (if there is one). Let's start with some screenshots including one of the Auctionator plugin settings.

Skillet-Classic gets the buyout data from Auctionator which gets its data from scanning the Auction House. There are two sorts that get data from Journalator but they have JNL: as a prefix.

While Skillet-Classic does the actual sort, I would expect complete chaos if there was something wrong with the sort algorithm. More likely is GIGO (i.e. bad data from Auctionator).

**Comment by Esc1972** [comment]
will report back with screenshots when it next misbehaves, working just now

**Comment by theoriginalmre** [comment]
Just to add to this discussion, I use Auctionator and have no problem with any glyphs being sorted via ATR Buyout. All the glyphs listed above I've checked through and are listed appropriately. This problem could be local to Journalator for the time being, or that since the prepatch, glyphs have seen a temporary uptick in sales and are moving very fast, causing the prices to sometimes fluctuate briefly inbetween scans of the AH, potentially throwing off the values. But I assume it's likely a bug with the Journalator data.

**Comment by b-morgan** [comment]
Just to be clear, I don't believe Journalator has anything to do with this issue. Journalator provides historical data primarily on **your** sales and postings on the Auction House. Auctionator can be used to scan the Auction House and provides a database of prices seen for items that are (or have been) posted by everyone.

Skillet-Classic has an Auctionator plugin that uses the Auctionator API to query its database for the buyout price of an item and (optionally) displays that in the Skillet-Classic frame. Skillet-Classic can sort the frame based on the values returned by the plugin.

I don't believe that the Skillet-Classic sort is unreliable but I can understand that the data supplied by Auctionator might be have unexpected values which are usually corrected by one (or more) scans of the Auction House.

**Comment by b-morgan** [comment]
Reopen this issue or open a new one if this happens again.
