### ISSUE TITLE
Queue Craftable Reagents not working

### ISSUE THREAD

**Issue by rbpaiett** [b-morgan/Skillet-Classic#17]
After the latest update (1.25) from WowInterface, 'Queue Craftable Reagents' is not working.

I queued a Mooncloth Bag and it needed 4 bolts of runecloth and all I had was runecloth in my inventory.  It didn't add 4 runecloth to the queue, just to the shopping list.

Just to be sure, after I did the update, I deleted the saved variables and still no joy.

**Comment by b-morgan** [comment]
I'm not sure what is happening on your system but on my system, its working as expected.

![QueueCraftableOff](https://user-images.githubusercontent.com/1547854/120324106-7860ce00-c2a3-11eb-9f61-36e7f3a2c280.jpg)
![QueueCraftableOn](https://user-images.githubusercontent.com/1547854/120324118-7e56af00-c2a3-11eb-8ca2-0dfcf2c99dae.jpg)

I guess we need to go through the standard troubleshooting steps. 

1. Disable all addons except Skillet-Classic
2. Login, type "/skillet debugshow on", "/skillet tabledump on", "/skillet debuglevel 2"
3. Open Tailoring
4. Verify state of Queue craftable reagents.
5. Close Tailoring
6. Open tailoring (this should assure that the server has delivered the correct data to the client).
7. Queue Mooncloth Bag
8. Open Shopping List, adjust position so it doesn't overlap with the main Skillet-Classic frame, take a screenshot.
9. Change state of Queue craftable reagents.
10. Clear Queue
11. Queue Mooncloth Bag
12. Take another screenshot.
13. Close Skillet-Classic and logoff
14. Zip your global saved variables file, Skillet-Classic.lua, and this character's saved variables file, Skillet-Classic.lua (rename if you put both in the same .zip file) and upload (drag them to this window) the screenshots and the zip file(s).

You can turn off Skillet-Classic chat debugging with "/skillet debugshow off" and the saved variable debugging with "/skillet debuglogging off". The saved variable logging is limited in size keeping only the most recent data and has minimal performance impact so I leave it on all the time.

I'll look at your data and decide what to do next.

**Comment by rbpaiett** [comment]
I think it's just with the mooncloth bag but I'll go through the steps.

**Comment by rbpaiett** [comment]
[Skillet Mooncloth Bag Issue.zip](https://github.com/b-morgan/Skillet-Classic/files/6597377/Skillet.Mooncloth.Bag.Issue.zip)

Ok, I wasn't sure whether you wanted the screenshots here in the message or in the zip file but they are included in the upload.

**Comment by b-morgan** [comment]
I figured out where to put an option so the next build will have "Ignore banked reagents".

**Comment by rbpaiett** [comment]
Yes please, that would be great!  It would make it so I use my raw materials in by inventory before heading to the bank :)

**Comment by b-morgan** [comment]
Try [Skillet-Classic-1.27-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/3338195)
