### ISSUE TITLE
Enhancement - mass add recipes to the queue

### ISSUE THREAD

**Issue by theoriginalmre** [b-morgan/Skillet-Classic#170]
Currently, if I wish to craft 3 separate recipes in a Queue, I need to:
- click on Recipe 1,
- click Queue
- click on Recipe 2,
- click Queue
- click on Recipe 3,
- click Queue
- click Process x3 times

I would like to instead be able to highlight all 3 recipes (ctrl+click all 3 so they are selected), then add them all in bulk to the queue. Either with a button that says "Add All to Queue" or via the right-click menu.

**Comment by theoriginalmre** [comment]
No unfortunately this is not what I need.

A long time ago back when I used TSM, it had the feature I'm requesting. (But I hate TSM so I'm not using it now lol.) That is, the ability to craft items dynamically that I don't already have in my inventory or on the AH.

Using glyphs as an example, if I decide to craft the 50 most profitable glyphs, then after an hour I've sold half of them, I want to be able to quickly use Skillet to check what I've still got in my bags (or AH), which I currently can, and then select the 25 missing glyphs and craft them again to relist. 

At the moment, I have to click on the glyph, then go click queue, then repeat this process 25 times etc. It becomes extremely tedious. I just want to add the items to the queue that I've currently missing from my list, in a quick way.

**Comment by b-morgan** [comment]
How do you determine the 25 missing glyphs (screenshot might be helpful)?

**Comment by theoriginalmre** [comment]
![Untitled](https://github.com/b-morgan/Skillet-Classic/assets/26218469/f1e21c43-0c24-43b8-ac9e-9aaa38186ec8)

Skillet shows me :)
The blue column is how many I have / don't have.

**Comment by b-morgan** [comment]
Not as complicated as I thought...

Replace ...\Skillet-Classic\UI\Mainframe.lua with the one in the .zip file. Ctrl-click to select and right-click "Queue".

[MainFrame.zip](https://github.com/b-morgan/Skillet-Classic/files/15253101/MainFrame.zip)

**Comment by theoriginalmre** [comment]
This works PERFECT! <3

The only other suggestion I would ask is whether it's possible to have a key like Spacebar assigned so that that when the Skillet Window is open, pressing Spacebar activates the "Process" button.

**Comment by b-morgan** [comment]
Add the file from the following .zip file to `...\Interface\Addons\Skillet-Classic` and use "Options", "Gameplay", "Keybindings" to set the key you want.

[Bindings.zip](https://github.com/b-morgan/Skillet-Classic/files/15255379/Bindings.zip)

**Comment by theoriginalmre** [comment]
While that bindings file does technically do the job, I was hoping for something more like what Auctionator does, and allows you to keybind an existing keybind to Auctionator that only functions when the AH window is open.

Eg, I have Spacebar bound to toggle auto run, but when I open the AH, I can press spacebar to post/cancel auctions with Auctionator without having to erase my existing keybind. Then when I close the AH, the spacebar key reverts back to my default setting.

![image](https://github.com/b-morgan/Skillet-Classic/assets/26218469/46d5e495-3e36-43dd-ab00-928a7757d230)

**Comment by b-morgan** [comment]
> So I was hoping that I could have a key that only functions when the Skillet window is open.

The author of Auctionator, Journalator, etc. is a true addon author genius. 

Now you are asking for a complicated solution involving new UI elements, etc.

I'll look into it but don't hold your breath.

**Comment by theoriginalmre** [comment]
I'm more than happy with the current changes to mainframe section <3
If you did the key function that would be a bonus. Thanks for everything!
