### ISSUE TITLE
Vanishing Powder throwing an error

### ISSUE THREAD

**Issue by Penaiel** [b-morgan/Skillet-Classic#171]
I am a Inscription [255] crafter that love your add-on.

But recently your latest release 1.90-alpha1 (what I am currently using) throws this error when I try to see the recipe for Vanishing Powder

1x Skillet-Classic/UI/MainFrame.lua:1841: Usage: self:SetValue(value)
[string "=[C]"]: in function `SetValue'
[string "@Skillet-Classic/UI/MainFrame.lua"]:1841: in function `UpdateDetailsWindow'
[string "@Skillet-Classic/UI/MainFrame.lua"]:975: in function `UpdateTradeSkillWindow'
[string "@Skillet-Classic/UI/MainFrame.lua"]:2524: in function `ScrollToSkillIndex'
[string "@Skillet-Classic/Skillet.lua"]:1600: in function `SetSelectedSkill'
[string "@Skillet-Classic/UI/MainFrame.lua"]:2445: in function `SkillButton_OnClick'
[string "*MainFrame.xml:359_OnClick"]:2: in function <[string "*MainFrame.xml:359_OnClick"]:1>

Locals:
(*temporary) = SkilletRankFrameRed {
 0 = <userdata>
}
(*temporary) = nil

Normal glyphs works fine but is only VP that gives that error.

**Comment by b-morgan** [comment]
This is fixed in Skillet-Classic-1.90-alpha2 or Skillet-Classic-1.90
