### ISSUE TITLE
Proff window (enchanting) will sometimes stop coming up for no apparent reason

### ISSUE THREAD

**Issue by panlakes1** [b-morgan/Skillet-Classic#172]
Sometimes when I open my enchanting, nothing will happen besides my bags opening. This will persist even when I exit my game or re-enable the addon or change toons. I can work around it by: opening tailoring, manually clicking the enchanting icon in skillet, and while the "click okay" skillet error message remains on screen - pressing my ench hotkey on my action bars. This will open the blizz proff window instead of skillet, but if I close the error message the blizz window will disappear as well, and obviously in this state I can't use any skillet features. 
 
Happens on my tailoring & enchanting toon, specifically enchanting is the issue. Very random, sometimes the problem won't occur in a session at all, sometimes it'll bug out after a couple crafts and window changes, other times it'll happen immediately when I log in for the day. It most commonly happens after I've changed proff windows, mainly tailoring -> enchanting.

I've disabled all my addons until only skillet remains, problem disappears when disabling skillet but obviously not ideal since I want to use the addon lol

Sorry if it's not able to be reproduced. Let me know if you need other info that I didn't include.

**Comment by b-morgan** [comment]
Reopen this issue and supply the requested information.
