### ISSUE TITLE
AtlasLoot causing error in Skillet:SkillButton_OnEnter

### ISSUE THREAD

**Issue by Jockulation** [b-morgan/Skillet-Classic#174]
Addon Version: 1.91 Cata
Game Version: 4.4.0

I get this error whenever mousing over an item in the AtlasLoot "Crafting" section.

376x Usage: local count = C_Item.GetItemCount(itemInfo [, includeBank, includeUses, includeReagentBank])
[string "=[C]"]: in function `GetItemCount'
[string "@Skillet-Classic/UI/MainFrame.lua"]:1529: in function `SkillButton_OnEnter'
[string "*MainFrame.xml:374_OnEnter"]:3: in function <[string "*MainFrame.xml:374_OnEnter"]:1>

Locals:
(*temporary) = "Usage: local count = C_Item.GetItemCount(itemInfo [, includeBank, includeUses, includeReagentBank])"

**Comment by b-morgan** [comment]
I'm not sure how Skillet-Classic is being referenced in AtlasLoot but AtlasLoot has not been updated for Cataclysm Classic. In any case, I can't reproduce this error. Can you please describe the steps you take to get this error to occur. Add some screenshots if that will help.

Until I understand how Skillet-Classic is involved, I can't generate a proper fix. Replacing `...\Interface\Addons\Skillet-Classic\UI\MainFrame.lua` with the one in the following .zip file will eliminate the error but I have no idea if any information displayed is accurate.

[MainFrame.zip](https://github.com/user-attachments/files/15534355/MainFrame.zip)

**Comment by Jockulation** [comment]
I did a bit more testing.  It would seem, with just [AtlasLootClassic_Cata](https://github.com/snowflame0/AtlasLootClassic_Cata), BugSack, BugGrabber and Skillet enabled there were zero issues.    

The moment I enable [ShestakUI](https://github.com/EsreverWoW/ShestakUI_Classic) with the above addons, it starts spitting out the error whenever I mouse over something in Atlasloot.

**Comment by b-morgan** [comment]
I'm afraid this issue is out of my control. 

With ShestakUI, AtlasLootClassic_Cata, BugSack, BugGrabber, and **NO Skillet-Classic** I get the error.
