### ISSUE TITLE
Chat message when entering combat

### ISSUE THREAD

**Issue by asa-git** [b-morgan/Skillet-Classic#179]
Hi,

I've installed the new version released today.
But now every time i enter into combat, while not even using the addon at that time, i get the following message on my chat box:
[15:20:43] Skillet-Classic: Skillet-Classic: Combat lockdown restriction. Leave combat and try again. 

Best regards.

**Comment by b-morgan** [comment]
That's not supposed to happen... I'll see if I can reproduce (and fix) it.

**Comment by b-morgan** [comment]
This is fixed in Skillet-Classic-1.93.

**Comment by asa-git** [comment]
ty :)
