### ISSUE TITLE
Lua Error - 

### ISSUE THREAD

**Issue by Dejoule** [b-morgan/Skillet-Classic#18]
1x [ADDON_ACTION_BLOCKED] AddOn 'Skillet-Classic' tried to call the protected function 'SkilletFrameTradeButtons-Horologist:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function Show' [string "@Skillet-Classic\UI\MainFrame.lua"]:709: in function UpdateTradeButtons'
[string "@Skillet-Classic\UI\MainFrame.lua"]:881: in function UpdateTradeSkillWindow' [string "@Skillet-Classic\UI\MainFrame.lua"]:2352: in function ScrollToSkillIndex'
[string "@Skillet-Classic\Skillet-20501.nil.lua"]:1416: in function SetSelectedSkill' [string "@Skillet-Classic\UI\MainFrame.lua"]:2273: in function SkillButton_OnClick'
[string ":OnClick"]:2: in function <[string ":OnClick"]:1

Do not know how to replicate, I'll keep trying

**Comment by b-morgan** [comment]
If you haven't already, please type "/skillet debuglogging on" so that we will have the debug output if this error occurs again.

**Comment by Dejoule** [comment]
I haven't been able to recreate this error in the past two days, recommend this issue be closed.

**Comment by b-morgan** [comment]
I'll leave it open for now in the hope that you or someone else will capture some additional data and add it here.

**Comment by b-morgan** [comment]
Please open a new issue if this happens again.
