### ISSUE TITLE
SetValue(value) error

### ISSUE THREAD

**Issue by Brum8842** [b-morgan/Skillet-Classic#184]
I am getting this error when I try to click on the Transmute: Fire to Earth in Alchemy

3x Skillet-Classic/UI/MainFrame.lua:1838: Usage: self:SetValue(value)
[string "=[C]"]: in function `SetValue'
[string "@Skillet-Classic/UI/MainFrame.lua"]:1838: in function `UpdateDetailsWindow'
[string "@Skillet-Classic/UI/MainFrame.lua"]:971: in function `UpdateTradeSkillWindow'
[string "@Skillet-Classic/UI/MainFrame.lua"]:2537: in function `ScrollToSkillIndex'
[string "@Skillet-Classic/Skillet.lua"]:1611: in function `SetSelectedSkill'
[string "@Skillet-Classic/UI/MainFrame.lua"]:2458: in function `SkillButton_OnClick'
[string "*MainFrame.xml:359_OnClick"]:2: in function <[string "*MainFrame.xml:359_OnClick"]:1>

Locals:
(*temporary) = SkilletRankFrameGreen {
 0 = <userdata>
}
(*temporary) = nil

This is Skillet-Classic 1.96 (40400).

**Comment by b-morgan** [comment]
Unfortunately, my Cataclysm Classic Alchemist isn't high enough level to have that recipe.

Please extract the files from the following zip into ...\Interface\Addons\Skillet-Classic (`SkillLevelData.lua` should go in the `Skillet-Classic` folder and `MainFrame.lua` should go in the `Skillet-Classic\UI` folder).

[Skillet-Classic.zip](https://github.com/user-attachments/files/16922637/Skillet-Classic.zip)

If these two files do not fix the issue, then I will need you to turn on Skillet-Classic debugging using the following chat commands:

1. `/skillet debuglevel 2`
2. `/skillet tabledump`
3. `/skillet debuglogging`

This will output to the character specific saved variables file in 
`...\WTF\Account\<name>\<realm>\<character>\SavedVariables\Skillet-Classic.lua`. Please reproduce the issue, logoff, and upload a zip of that file here.

Type `/skillet debugoff` to turn debugging off.

I'll have a look at that file and provide further instructions.

**Comment by Brum8842** [comment]
Those two files has fixed the issue, I am able to see the recipe in the window when I select it from the list now.
