### ISSUE TITLE
Consisten error whilst playing.

### ISSUE THREAD

**Issue by ERFmama** [b-morgan/Skillet-Classic#2]
18x Skillet-Classic\Skillet-11306.nil.lua:1135: attempt to call method 'InventoryScan' (a nil value)
Skillet-Classic\Skillet-11306.nil.lua:1135: in function `?'
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by b-morgan** [comment]
I'm 99% certain that you have a corrupted install. Go to [https://www.curseforge.com/wow/addons/skillet-classic/files](url), click the download icon and then check the MD5 checksum using [winMD5sum](https://sourceforge.net/projects/winmd5sum/).

Delete the `...\World of Warcraft\_classic_\Interface\Addons\Skillet-Classic` folder and install the above zip in `...\Interface\Addons`. Let me know if that fixes the issue.

**Comment by b-morgan** [comment]
I assume I was right so I'm closing this issue.
