### ISSUE TITLE
Suggestion: Favourite crafts

### ISSUE THREAD

**Issue by ZehelFenris** [b-morgan/Skillet-Classic#21]
Do so we can favourite crafts so they always show regardless of which skill difficulty threshold is selected.
I like to always have my threshold on green but i would also like to be able to keep seeing my make bolts on my tailor even after it turns grey.

**Comment by b-morgan** [comment]
While not exactly what you ask for, Skillet-Classic has the ability to create custom groups with whatever recipes you wish to have in each group. Use the small arrow next to the Grouping dropdown to create a group and use left-click, ctrl-left-click, shift-left-click to select one or multiple recipes from the list and right-click to take action on the selected recipes. Actions include copy, cut, paste, etc.

You can have multiple custom groups and a recipe can be in more than one group.
