### ISSUE TITLE
llua error on profession jewelcrafting

### ISSUE THREAD

**Issue by ncplus0** [b-morgan/Skillet-Classic#23]
when i open skillet and use it start to give 2 errors but still works

`2x [ADDON_ACTION_BLOCKED] AddOn 'Skillet-Classic' tried to call the protected function 'SkilletFrame:Hide()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `Hide'
Skillet-Classic\Skillet-11303.nil.lua:1204: in function `HideTradeSkillWindow'
Skillet-Classic\Skillet-11303.nil.lua:1217: in function <Skillet-Classic\Skillet.lua:1213>
(tail call): ?
Skillet-Classic\UI\MainFrame.lua:2523: in function <Skillet-Classic\UI\MainFrame.lua:2521>
[C]: in function `securecall'
FrameXML\UIParent.lua:2724: in function `CloseWindows'
FrameXML\UIParent.lua:2749: in function <FrameXML\UIParent.lua:2739>
[C]: in function `securecall'
FrameXML\UIParent.lua:3371: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>`

and also bug 

`5x Skillet-Classic\UI\MainFrame.lua:1390: Invalid trade skill item in SetTradeSkillItem(index [,reagent])
[string "=[C]"]: in function `SetTradeSkillItem'
[string "@Skillet-Classic\UI\MainFrame.lua"]:1390: in function `SkillButton_OnEnter'
[string "*:OnEnter"]:3: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = SkilletTradeskillTooltip {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:239
 backdropBorderColor = <table> {
 }
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:477
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:381
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:416
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:369
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:496
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:434
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:353
 comparing = false
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:301
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:269
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:365
 BottomOverlay = <unnamed> {
 }
 0 = <userdata>
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:275
 updateTooltip = 0.200000
 TopRightCorner = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 backdropColor = <table> {
 }
 Center = <unnamed> {
 }
 backdropInfo = <table> {
 }
 BottomEdge = <unnamed> {
 }
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:509
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:333
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:486
 LeftEdge = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
}
(*temporary) = 5
`

**Comment by b-morgan** [comment]
What version of Skillet-Classic? What locale? Where did you download from?

I suspect you have either a corrupted addon, a corrupted saved variables file, or interference from another addon. Based on the errors above, I'm leaning strongly towards a corrupted version of Skillet-Classic.

Please download [this one](https://www.curseforge.com/wow/addons/skillet-classic/files/3354360) and verify its MD5 checksum (2810170b1674d2236a8b25cc8b4a1869).

**Comment by ncplus0** [comment]
ive installed the version you said and it worked.
i was installing from the curse app and it was the same version 1.28.
so it was someting wrong with the files downloaded
tks for the help
