### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Brondy90** [b-morgan/Skillet-Classic#24]
Would it be possible to sort recipes by cost and/or profits? My head is spinning to check them one by one.

**Comment by b-morgan** [comment]
Attached is a replacement for `...\Addons\Skillet-Classic\UI\Sorting.lua` which adds a "Sort by suffix". The suffix is provided by one of the existing plugins. The Auctionator plugin is the one I use most often. If the Grouping is set to Blizzard, then the sort is within each category. If the Grouping is set to flat, then the sort is across all recipes. If you have created custom groups, then you'll figure it out.

[Sorting.zip](https://github.com/b-morgan/Skillet-Classic/files/6680550/Sorting.zip)

Let me know if this meets your needs, if you find any bugs, or if you just have questions. I plan to include this in the next build.

**Comment by Brondy90** [comment]
Fantastic you were very fast, if you need to know I use Auctionator.
However it works great, now to be greedy I would like a separate sorting only for "ATR Buyout" and another only for "Cost".

Then if you succeed in the impossible and have time to waste, it would be great if the plugin could optionally consider the average values of Profit, ATR Buyout or Cost over the course of the week. Acutionator has a "history" that makes me understand more or less the fluctuation of the items. With an average value I would be able to avoid items that have been auctioned with unusual values.

**Comment by b-morgan** [comment]
I had the same enhancement request for Skillet (retail) a while ago. I just forgot to port it to Skillet-Classic.

I'm not going to complicate the Skillet-Classic sorting dropdown with addon specific options but if you want to enhance the Auctionator plugin to provide different suffix values, then go for it. I'll consider including your enhanced version in a future build.

The Skillet-Classic Auctionator plugin gets its data from the Auctionator API. You will have to research that API to determine if the data you desire is available. I believe Auctionator development is concentrating on retail and the classic port is being maintained by someone outside the development team.

**Comment by Brondy90** [comment]
Thank you very kind, one last thing is there a way to manually add single items to the shopping list, without the recipe being in the queue? Probably there is already a way but I'm too stupid to understand how.

**Comment by b-morgan** [comment]
There is not a way to manually add items to the shopping list.
