### ISSUE TITLE
Skillet freezes the game for about 1s after closing the window

### ISSUE THREAD

**Issue by Elleden** [b-morgan/Skillet-Classic#27]
Following the latest update, Skillet started freezing my game for about 1s after closing the profession window.

If the cursor was on a crafting item at the time of closing (via escape), the crafting materials would stay on-screen even with no window, and the only way to remove them is to open the Skillet window again, mouseover something else, move the cursor away from the window, and then close it.

![image](https://user-images.githubusercontent.com/86515140/123508400-7f46ea80-d66f-11eb-81bd-f7b9e4e25805.png)

![image](https://user-images.githubusercontent.com/86515140/123508457-e9f82600-d66f-11eb-9d59-c71656d2c69c.png)

**Comment by b-morgan** [comment]
Please provide a specific version number as "latest update" doesn't tell me enough.

**Comment by b-morgan** [comment]
If "latest update" was Skillet-Classic-1.29-alpha, then please try [Skillet-Classic-1.29-alpha5](https://www.curseforge.com/wow/addons/skillet-classic/files/3365364)

**Comment by Elleden** [comment]
Ah, sorry, forgot the specific version number in the post. Pretty sure it was _Skillet-Classic-1.29-alpha_

But yeah, just updated to _Skillet-Classic-1.29-alpha5_ and the problem is gone. No more freezes.

**Comment by b-morgan** [comment]
Fantastic!
