### ISSUE TITLE
Localization missing

### ISSUE THREAD

**Issue by anon1231823** [b-morgan/Skillet-Classic#3]
Looks like under the "show recipes that you have all the materials for" the strings "Left-click to toggle"and "Right-click for filtering options" are not in the locale table in curseforge

**Comment by b-morgan** [comment]
Those phrases have been added to the [Skillet-Classic](https://www.curseforge.com/wow/addons/skillet-classic/localization) and the [Skillet](https://www.curseforge.com/wow/addons/skillet/localization) localization and the source files have been updated. The next build for both projects will pick up the current translations (which will still be English unless a volunteer translator help out) for those strings.

I assume you are playing on a non enUS locale so please feel free to add the translation for your locale and if you can do both Skillet-Classic and Skillet that would be fantastic!

**Comment by b-morgan** [comment]
This should be fixed in Skillet-Classic 1.22.
