### ISSUE TITLE
Basic Campfire Button

### ISSUE THREAD

**Issue by zhavier042** [b-morgan/Skillet-Classic#30]
I have recently noticed the basic campfure button does not appear.

**Comment by b-morgan** [comment]
I have recently noticed that Zhavier does not know how to cook :-) The button only appears if your character can use it.

At least, Skillet-Classic doesn't think so. The function that figures this out is in SkilletData.lua lines 144-181. There are three debug statements in that function that are commented out. Uncomment them (remove the "--"), turn on debugging, "/skillet cleardebuglog", logout, login, logout again and send me the saved variables (I want to capture the debug output as you login which is when the function is called).

Your global saved variables file contains the following table: 
```
			["tradeSkills"] = {
				["Zhavier"] = {
					[3908] = {
						["isCraft"] = false,
						["name"] = "Tailoring",
						["opened"] = 1641828.195,
						["count"] = 0,
						["maxRank"] = 375,
						["rank"] = 359,
					},
					[3273] = {
						["isCraft"] = false,
						["name"] = "First Aid",
						["opened"] = 1641834.828,
						["count"] = 0,
						["maxRank"] = 375,
						["rank"] = 361,
					},
				},
			},
```

**Comment by zhavier042** [comment]
Ah, i didnt have any wood, so thats why no button.  Got it, thanks!
