### ISSUE TITLE
Closing the skillet window with Escape

### ISSUE THREAD

**Issue by zhavier042** [b-morgan/Skillet-Classic#31]
I recently noticed that when I close the skillet window using the escape key, the wow options menu opens at the same time as closing the skillet window.  In addition, if the options menu is already open, the skillet window does not close, but the options menu does close.

**Comment by b-morgan** [comment]
I'm pretty sure there's nothing I can do about this one (other than remove the ability). When Skillet-Classic creates the frame(s) the following code is executed:
```
--
-- so hitting [ESC] will close the window
--
	tinsert(UISpecialFrames, frame:GetName())
```
After that, how the Escape key is handled is completely out of my control.
