### ISSUE TITLE
Silver Rod - Skill range (orange/yellow/green) not displayed

### ISSUE THREAD

**Issue by matthewhively** [b-morgan/Skillet-Classic#32]
version 1.29 (20501)

![skillet](https://user-images.githubusercontent.com/25018092/125163364-ad353000-e141-11eb-8871-8ca18ac87669.png)

**Comment by b-morgan** [comment]
The Blizzard API does not provide this data, it is supplied by addons. TradeSkillInfo was the best source but it has not been ported to Classic Era or Burning Crusade Classic. LibPeriodicTable-3.1 is another source that is available on Classic Era and Burning Crusade Classic but apparently, it does not contain data for the Silver Rod.

Skillet Classic has a (currently empty) table where this data could be inserted. See the file SkillLevelData.lua for details. I have no plans to maintain data for this table but it is there if you want to provide the data yourself. It looks like Wowhead has the info for the [Silver Rod](https://tbc.wowhead.com/spell=7818/silver-rod).

**Comment by matthewhively** [comment]
So, I should submit an issue with that lib author?

**Comment by b-morgan** [comment]
You could try but I haven't had much success in the past, [https://www.curseforge.com/wow/addons/libperiodictable-3-1](https://www.curseforge.com/wow/addons/libperiodictable-3-1).

What I have done is modify SkillLevelData.lua to add a global table, `Skillet.db.global.MissingSkillLevels` (so it will be found in the global saved variables file). You can lookup the missing items at [Wowhead ](https://tbc.wowhead.com/) and either add them manually to SkillLevelData.lua or write you own addon to populate the Skillet-Classic table via the provided function(s) `Skillet:AddTradeSkillLevels(spellID, orange, yellow, green, gray)` and `Skillet:DelTradeSkillLevels(spellID)`.

Writing your own addon is probably preferable as then updates to Skillet-Classic won't wipe out your data.

These changes will appear in the next build.

**Comment by b-morgan** [comment]
Skillet-Classic-1.30-alpha4 contains the changes to SkillLevelData.lua and other associated files. I added the Silver Rod to the table initialization.

Here are some other entries I found while debugging (all are from Enchanting):
```
			[-14807] = "70/110/130/150",
			[-25124] = "45/55/65/75",
			[-7454] = "45/95/115/135",
			[-7421] = "1/5/7/10",
			[-14293] = "10/75/95/115",
```
The process is to open Skillet-Classic to each of your professions, click each recipe and those without any data will be added to the `MissingSkillLevels` table in the global saved variables file (saved after you logoff). You then go to [https://tbc.wowhead.com/spell=7818](https://tbc.wowhead.com/spell=7818) (change the number) and the data needed should be found in the Quick Facts. You can then move the updated entries from the `MissingSkillLevels` table to the `SkillLevels` table.

This is a labor intensive, manual process and I will not be making regular updates. If, however, you wish to contribute to the project, I will accept an updated SkillLevelData.lua file for inclusion in future builds.

**Comment by matthewhively** [comment]
@b-morgan 
I've been fiddling with this a little bit.
As a note, the new demonstration of this localized DB
```
function Skillet:InitializeSkillLevels()
	self.db.global.SkillLevels = {
		[0] = "orange/yellow/green/gray",
        [7818] = "100/105/107/110",
	}
end
```
Is not working because 7818 is the spell id, but apparently skillet is looking for the item id 6338 instead.

Also is there any way to force skillet to re-run `InitializeSkillLevels`? I know I can delete the DB entry from SavedVariables/skillet-classic.lua but I'm hoping for something like `/reload`

**Comment by b-morgan** [comment]
You are correct, you have to get the levels from the [spell page](https://tbc.wowhead.com/spell=7818/silver-rod) but the table is looking for the [itemID](https://tbc.wowhead.com/item=6338/silver-rod). I'll fix the table in InitializeSkillLevels in the next build.

If you want to run the function again, type `/run Skillet:InitializeSkillLevels()` or `/run Skillet:DelTradeSkillLevels(7818)` to remove the bogus entry (but it doesn't hurt to leave it in there as that [itemID](https://tbc.wowhead.com/item=7818) doesn't exist.

As I stated before, I have no intention of maintaining this table as doing so is currently a very labor intensive, manual process. Other people have written scripts to datamine Wowhead but I'll leave that to someone else.
