### ISSUE TITLE
Hunter/Pet? Error

### ISSUE THREAD

**Issue by Mixuspidelix** [b-morgan/Skillet-Classic#34]
i get said error message when I want to teach my pet new things via the animal training window

Message: Interface\AddOns\Skillet-Classic\Skillet.lua:848: attempt to perform arithmetic on field 'craftUpdate' (a nil value)
Time: Wed Jul 21 18:35:43 2021
Count: 15
Stack: Interface\AddOns\Skillet-Classic\Skillet.lua:848: attempt to perform arithmetic on field 'craftUpdate' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Skillet-Classic\Skillet.lua"]:848: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by b-morgan** [comment]
Fixed in [Skillet-Classic-1.31-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/3398774).
