### ISSUE TITLE
reagents not listing

### ISSUE THREAD

**Issue by manticode** [b-morgan/Skillet-Classic#40]
Selecting certain items (alchemy or cooking in my case) does not list the materials required, either no ingredients at all or only 1 or 2 items. This does appear to somewhat resolve itself in time or by closing and reopening Skillet some time later.

**For example:**

- Click on Cooking -> Spicy Hot Talkbuk
- By Reagents there are no materials listed

**Another example:**

- Click Cooking -> Gingerbread Cookie
- Under reagents only 1 x Small Egg is showing, Holiday Spices is missing
(logging out and back in seemed to resolve this in this case)

**Alchemy example:**

- Click Alchemy -> Mageblood Potion
- Reagents show only 1 x Dreamfoil required  (expect 1 x Dreamfoil, 2 x Plaguebloom and 1 x Crystal Vial)
- (logging out and back in resolved this)

Using Skillet-Classic 1.31 (20501) on WoW TBC Classic 2.5.1 (39603)

**Comment by b-morgan** [comment]
I have been trying to fix this issue for a long time. The definitive source of your profession(s) knowledge is the server. The API functions used (by Skillet-Classic) to query this knowledge ask the client. If the client isn't yet synced to the server (which is the case when you first login), the API functions will return incomplete data (i.e. they lie). The API generates events when the server updates the client and Skillet-Classic registers for and uses these events to scan the profession. Unfortunately, there is no event that says "the client is completely synced with the server", only event(s) that say "the client knows more than before".

Logging out and back in is not the way to fix this issue, closing and reopening Skillet-Classic is. Once the client is synced with the server, it will stay in sync for the entire session. Note that if both of your primary professions rely on each other (i.e. Blacksmithing / Mining or Engineering / Mining) then both need to be synced with the server.

Unfortunately, with my internet connection and client computer configuration, I can't get this to reproduce often enough to make any progress on a definitive fix. I have studied the Blizzard UI and duplicated its functionality as best I can but obviously, I haven't got it right yet.

In `...\Interface\Addons\Skillet-Classic\Skillet.lua` lines 833 and 854 are commented out ("--" at the beginning of the line). Remove the "--" so these lines are now:
```
	if Skillet.tradeUpdate < 2 then return end
	if Skillet.craftUpdate < 2 then return end
```
and see if that reduces the occurrence of this issue. If not, change the 2 to 3 (or more). The risk is that the number of update events isn't fixed and if this number gets too high, the Skillet-Classic window just won't open. Let me know if it helps. I may have to add an option to Skillet-Classic so people with this issue can tune their systems without having to modify the sources.

**Comment by b-morgan** [comment]
Closing issue as there has been no response.
