### ISSUE TITLE
Virus detected 

### ISSUE THREAD

**Issue by bozephalus** [b-morgan/Skillet-Classic#43]
Trojan:Script/Wacatac.B!ml

Is detected during installation process, not sure yet if it is related to the installationfile or your code, might be false positive but not sure.

**Comment by daBernd** [comment]
same here, I reinstalled the previous version without any issue.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.32.zip](https://www.curseforge.com/wow/addons/skillet-classic/download/3432448) from the [Skillet-Classic](https://www.curseforge.com/wow/addons/skillet-classic) Curseforge website, passes an MD5 checksum check, and passes a [Virustotal](https://www.virustotal.com/gui/home/upload) check.

I installed that .zip file on my system and scanned for viruses with Malwarebytes and Windows Defender successfully.

Can you tell me how and where you obtained your file and what program detected the virus?

**Comment by Raykefire** [comment]
Windows Defender
Detected: Trojan:Script/Wacatac.B!ml
This program is dangerous and executes commands from an attacker.
file: C:\Users\X\Downloads\Skillet-Classic-1.32-classic.zip
webfile: C:\Users\X\Downloads\Skillet-Classic-1.32-classic.zip|https://media.forgecdn.net/files/3432/448/Skillet-Classic-1.32-classic.zip|pid:25348,ProcessStart:132740235375690162

Detects if on direct download and from the curseforge app.

**Comment by b-morgan** [comment]
I don't know what I can do about this. My direct download from Curseforge is virus free. I have verified that the directly downloaded file has the same MD5 checksum as posted on the Curseforge page. I have scanned the downloaded file on my system with Windows Defender and Malwarebytes.

What I still need to know is how and where your file was obtained. There are multiple addon sites that host Skillet and Skillet-Classic and one of them could have a corrupted file, but I can't fix it if I don't know which one.

**Comment by Raykefire** [comment]
https://www.curseforge.com/wow/addons/skillet-classic?__cf_chl_jschl_tk__=pmd_lDbjPejZXWUL1dxk8wVc0SLDaGnE_gcuFkddAvHjUG0-1629591791-0-gqNtZGzNAeWjcnBszQsl

It also does it when using the Curseforge beta installer.

**Comment by b-morgan** [comment]
> https://www.curseforge.com/wow/addons/skillet-classic?__cf_chl_jschl_tk__=pmd_lDbjPejZXWUL1dxk8wVc0SLDaGnE_gcuFkddAvHjUG0-1629591791-0-gqNtZGzNAeWjcnBszQsl
> 
I don't know what that string is after the "?". None of my links contain a string like that so I'm not clicking on it. I have posted links in this issue that I know work and do not contain a virus. 

I'm afraid you are on your own to figure this out. I'm closing this issue because I don't believe the 6,000+ people who have downloaded Skillet-Classic are all infected.
