### ISSUE TITLE
bug opening cooking tradeskill

### ISSUE THREAD

**Issue by MyTechnoHunter** [b-morgan/Skillet-Classic#47]
i clicked on the icon for first aid and had that window open.. i then clicked on the game icon for cooking and got the following

5x Skillet-Classic\SkilletData.lua:605: attempt to index field '?' (a nil value)
[string "@Skillet-Classic\SkilletData.lua"]:605: in function `GetSkill'
[string "@Skillet-Classic\SkilletData.lua"]:678: in function `CalculateCraftableCounts'
[string "@Skillet-Classic\SkilletQueue.lua"]:32: in function `AdjustInventory'
[string "@Skillet-Classic\Skillet-20502.nil.lua"]:846: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

closing the first aid window then opening the cooking window gave no error at that point then i was able to keep the windows open and switch between first aid and cooking.. 

hope that helps narrow it down

**Comment by b-morgan** [comment]
I'm going to guess that this happened the first time you were opening cooking after logging in. If so, then this is another manifestation of issues #40 and #45. The Blizzard API that Skillet-Classic uses queries the client but the data originates on the server. The API returns what the client knows at that time even if it is incomplete and/or wrong. Unfortunately, there's no event available to indicate that the client has all the data.

I have attempted to code Skillet-Classic to mimic the Blizzard UI and have obviously failed. I have asked for additional information in #40 and #45 but neither has responded. Until I can collect enough debug information to discover a pattern and develop a fix, this issue will remain unsolved.

Opening and closing each profession once at the beginning of each session appears to prevent these errors.

**Comment by b-morgan** [comment]
This particular error should be eliminated in Skillet-Classic-1.35-alpha1 and beyond. Please reopen this issue or open a new one if it happens again.
