### ISSUE TITLE
Guildbook and Skillet-Classic

### ISSUE THREAD

**Issue by b-morgan** [b-morgan/Skillet-Classic#48]
From https://github.com/b-morgan/Skillet/issues/26

![image](https://user-images.githubusercontent.com/47498931/133256004-78215ade-84d5-403a-9534-f49856ca11f0.png)

Hi so i've had this bug reported, have you noticed any issues when using guildbook?

Does skillet hide the default blizzard ui?

Regards

Sam

**Comment by b-morgan** [comment]
I have not noticed any issues with Skillet-Classic and Guildbook. My character's recipes appear in Guildbook. 

Both Skillet and Skillet-Classic hide the default Blizzard UI.

**Comment by b-morgan** [comment]
```
if Skillet and Skillet.tradeSkillFrame and not Skillet.tradeSkillFrame:IsVisible() then
```
or
```
if SkilletFrame and not SkilletFrame:IsVisible() then
```

You are going to have a similar problem with [Trade Skill Master](https://www.curseforge.com/wow/addons/tradeskill-master) when it is in its native mode.

**Comment by stpain** [comment]
I have written a different approach where i check if any new recipes were learnt to determine if an update is required.

**Comment by b-morgan** [comment]
Also Skillet-Classic and [https://zygorguides.com/](https://zygorguides.com/) have a conflict so Guildbook may as well.

**Comment by stpain** [comment]
Hmmm yeah.....paid for guides not something I care to go near personally.

**Comment by b-morgan** [comment]
Your different approach will probably cover the Zygor case as well.

**Comment by b-morgan** [comment]
I believe this issue has been resolved.
