### ISSUE TITLE
Incorrect version offered from curseforge app

### ISSUE THREAD

**Issue by MyTechnoHunter** [b-morgan/Skillet-Classic#49]
![image](https://user-images.githubusercontent.com/55214545/133923202-691c316f-9084-4fe2-8708-1706d7948988.png)

going to download the file manually from here, it was at 1.34, i reinstalled from curseforge and it installed 1.33? and the file from here says 1.35

**Comment by b-morgan** [comment]
There is nothing I can do about this. I update the project on CurseForge and WoWInterface and how users choose to keep their own systems updated is beyond my control. [Skillet-Classic-1.35-classic](https://www.curseforge.com/wow/addons/skillet-classic/files/3461381) is the latest version.

I notice that 1.33 has 15,000+ downloads but 1.34 and 1.35 have less than 500 combined so it doesn't surprise me that something is amiss with one or more of the addon managers. I use [WowUp.io](https://wowup.io/) and it appears to be working correctly.
