### ISSUE TITLE
TBC Compatibility

### ISSUE THREAD

**Issue by Dejoule** [b-morgan/Skillet-Classic#5]
At this time Skillet Classic and Skillet Retail do not function for TBC.

**Comment by b-morgan** [comment]
That is correct. I'm working on a Skillet-BBC version but it isn't ready yet.

**Comment by b-morgan** [comment]
Try Skillet-1.23-alpha2 and see if that works.

**Comment by Dejoule** [comment]
I'll give it a try. My main hope was that you would be continuing it for TBC, I heavily rely on it as opposed to scrolling through my entire enchanting list when somebody wants an enchant. Whether it's "out of date" is of no concern to me.

**Comment by b-morgan** [comment]
I assume that "the current alpha is functional for TBC beta" means Skillet-1.23-alpha2. I have always been planning to have a version of Skillet (or Skillet-Classic or Skillet-BCC) for this release. The only question was would it require a third set of sources.

I was leaning towards three sets until today when I decided to back port the changes I'd made into Skillet-Classic. There were only a couple of changes necessary to make the same files work on both. The only remaining issue is how to package a BCC version with the one line change to the .toc file.

**Comment by b-morgan** [comment]
Skillet-1.23-beta3-classic and Skillet-1.23-beta3-bcc are now available in the [files ](https://www.curseforge.com/wow/addons/skillet-classic/files)section of the project site.
