### ISSUE TITLE
TBC classic

### ISSUE THREAD

**Issue by wisenimrod** [b-morgan/Skillet-Classic#50]
i can not open the ingenieur skillbook with the addon on - any idea to fix it ?

**Comment by b-morgan** [comment]
I think I know what's wrong but I can't fix it without your help. In SkilletData.lua lines 64-79 is a table (copied below). I need to know:

1. Your version of WoW (Classic Era or Burning Crusade Classic)
2. Version of Skillet-Classic
3. Your locale (type "/dump GetLocale()")
4. The output from "/dump GetSpellInfo(tradeID)" where tradeID can be found in the table in SkilletData.lua lines 40-54)
5. The output from "/dump GetTradeSkillLine()" while the tradeskill in question is open (with the Blizzard UI).

If there are any special characters in either step 4 or 5, then I need them exactly as output. The easiest thing would be for you to update your local copy of SkilletData.lua and then test it. When it works, zip up your copy and attach it here. I'll update the master copy so it will work for you (and anyone else with your locale) in the future.

```
--
--  a table of locale specific translations by id
-- needed to fix Blizzard inconsistent translations
--
-- [tradeID] = {locale, old, new}
--   locale is what GetLocale() returns
--   old is the return from GetSpellInfo(tradeID)
--   new is the return from GetTradeSkillLine() when the tradeskill / craft is opened
--
local TranslateList = {
	[4036] = {"frFR", "Ingénieur", "Ingénierie"},			-- engineering
	[3273] = {"frFR", "Premiers soins", "Secourisme"},		-- first aid
	[2108] = {"esES", "Peletería", "Marroquinería"},		-- leatherworking
	[3908] = {"esES", "Sastrería", "Costura"},				-- tailoring
	[2108] = {"koKR", "가죽세공", "가죽 세공"},					-- leatherworking
}
```

**Comment by wisenimrod** [comment]
lines 64-79:
}

--
--  a table of locale specific translations by id
-- needed to fix Blizzard inconsistent translations
--
-- [tradeID] = {locale, old, new}
--   locale is what GetLocale() returns
--   old is the return from GetSpellInfo(tradeID)
--   new is the return from GetTradeSkillLine() when the tradeskill / craft is opened

**Comment by wisenimrod** [comment]
1. Your version of WoW (Classic Era or Burning Crusade Classic) - TBC Classic
    2. Version of Skillet-Classic - 1.35
    3. Your locale (type "/dump GetLocale()") - [1]="deDE"
    4. The output from "/dump GetSpellInfo(tradeID)" where tradeID can be found in the table in SkilletData.lua lines 40-54)
    --
local TradeSkillList = {
	2259,		-- alchemy
	2018,		-- blacksmithing
	4036,		-- engineering
	2108,		-- leatherworking
	SMELTING,	-- smelting
	MINING,		-- mining
	3908,		-- tailoring
	2550,		-- cooking
	3273,		-- first aid

    5. The output from "/dump GetTradeSkillLine()" while the tradeskill in question is open (with the Blizzard UI)

**Comment by wisenimrod** [comment]
i got now this error message:
sage: Interface\AddOns\Skillet-Classic\Skillet-20502.nil.lua:711: attempt to call method 'CollectTradeSkillData' (a nil value)
Time: Wed Sep 22 00:46:09 2021
Count: 1
Stack: Interface\AddOns\Skillet-Classic\Skillet-20502.nil.lua:711: attempt to call method 'CollectTradeSkillData' (a nil value)
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:68: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:63>
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:525: in function `EnableAddon'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:628: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:613>

**Comment by b-morgan** [comment]
Got one of the three things I need, your locale = "deDE". Now that I know that, I believe "ingenieur" is Engineering so I need the output of "/dump GetSpellInfo(4036)". Then I need you to open the Blizzard UI for Engineering (since Skillet-Classic won't open) and then the output of "/dump GetTradeSkillLine()" while the Engineering UI is visible.

**Comment by wisenimrod** [comment]
[07:33] Dump: value=GetTradeSkillLine() 
[07:33] [1]="Ingenieurskunst", 
[07:33] [2]=300, 
[07:33] [3]=375

**Comment by wisenimrod** [comment]
this was with the elvui on - should i do it with the blizzard ui ?

**Comment by b-morgan** [comment]
Two down, one to go... I need the value of "/dump GetSpellInfo(4036)".

**Comment by wisenimrod** [comment]
12:16] Dump: value=GetSpellInfo(4036) 
[12:16] [1]="Ingenieurskunst", 
[12:16] [3]=136243, 
[12:16] [4]=0, 
[12:16] [5]=0, 
[12:16] [6]=0, 
[12:16] [7]=4036

**Comment by wisenimrod** [comment]
sry didnt understand it

**Comment by b-morgan** [comment]
Now I'm the one that doesn't understand. Since the names match, you should be able to open "Ingenieurskunst" (Engineering) in Skillet-Classic. Hopefully, Github isn't getting in the way and they do match, i.e. there are no German specific characters in either string.

Please give me the output of "/dump Skillet.tradeSkillIDsByName" and "/dump Skillet.tradeSkillNamesByID".

**Comment by wisenimrod** [comment]
Message: [string "return Skillet.tradeSkillIDsByName"]:1: attempt to index global 'Skillet' (a nil value)
Time: Wed Sep 22 14:36:10 2021
Count: 1
Stack: [string "return Skillet.tradeSkillIDsByName"]:1: attempt to index global 'Skillet' (a nil value)
[string "@Interface\FrameXML\ChatFrame.lua"]:2395: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:4825: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4488: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4524: in function <Interface\FrameXML\ChatFrame.lua:4520>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: msg = "Skillet.tradeSkillIDsByName"

**Comment by wisenimrod** [comment]
[14:37] Dump: value=Skillet.tradeSkillIDsByName 
[14:37] [1]={ 
[14:37]   Alchimie=2259, 
[14:37]   Schneiderei=3908, 
[14:37]   Verzauberkunst=7411, 
[14:37]   ["Erste Hilfe"]=3273, 
[14:37]   Kochkunst=2550, 
[14:37]   Juwelenschleifen=25229, 
[14:37]   Ingenieurskunst=4036, 
[14:37]   Gifte=2842, 
[14:37]   Schmiedekunst=2018, 
[14:37]   Bergbau=2575, 
[14:37]   Lederverarbeitung=2108, 
[14:37]   ["Verhüttung"]=2656 
[14:37] }

**Comment by wisenimrod** [comment]
[14:38] Dump: value=Skillet.tradeSkillNamesByID 
[14:38] [1]={ 
[14:38]   [4036]="Ingenieurskunst", 
[14:38]   [2259]="Alchimie", 
[14:38]   [2575]="Bergbau", 
[14:38]   [3273]="Erste Hilfe", 
[14:38]   [7411]="Verzauberkunst", 
[14:38]   [25229]="Juwelenschleifen", 
[14:38]   [2108]="Lederverarbeitung", 
[14:38]   [2018]="Schmiedekunst", 
[14:38]   [2842]="Gifte", 
[14:38]   [2550]="Kochkunst", 
[14:38]   [3908]="Schneiderei", 
[14:38]   [2656]="Verhüttung" 
[14:38] }

**Comment by wisenimrod** [comment]
now its working - what a day - dont know what happens - didnt change anything
thanks a lot for your patience :D

**Comment by b-morgan** [comment]
Let me know if it happens again. I have found that after you first login, opening professions with Skillet-Classic can sometimes display bad data because the client hasn't fully synced with the server. If it does, close the profession and open it again and it should fix itself.

**Comment by wisenimrod** [comment]
i will do if its happen again - hope that not <3
