### ISSUE TITLE
Strange 1-off error when opening skillet.

### ISSUE THREAD

**Issue by matthewhively** [b-morgan/Skillet-Classic#53]
Version 1.33

I'm not sure what caused this. As I have not been able to reproduce it.
It happened when I switched from blacksmithing to smelting (using profession links on my hotbar), but this is the first time I've encountered this error.
But I got 2 errors at once.
```
Message: Interface\AddOns\Skillet-Classic\SkilletData.lua:565: attempt to index field '?' (a nil value)
Time: Mon Oct  4 01:10:35 2021
Count: 1
Stack: Interface\AddOns\Skillet-Classic\SkilletData.lua:565: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\Skillet-Classic\Skillet.lua"]:850: in function `?'
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Attune\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ace\AddOns\Attune\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>
```
and
```
Message: Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:1395: Invalid trade skill item in SetTradeSkillItem(index [,reagent])
Time: Mon Oct  4 01:14:44 2021
Count: 16
Stack: Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:1395: Invalid trade skill item in SetTradeSkillItem(index [,reagent])

Locals: 
```

It seems that skillet after encountering these errors is in a complete broken state. Every time I click another trade skill it repeats the first error. Closing skillet and re-opening restored it to normalcy.
I presume it has something to do with loading data from the server.
Very strange.

**Comment by matthewhively** [comment]
In the same session, I got this after I logged on to my bank alt.
```
Message: Error loading Interface\AddOns\Skillet-Classic\Plugins\Auctipus.lua
Time: Mon Oct  4 01:32:42 2021
Count: 3
Stack: Error loading Interface\AddOns\Skillet-Classic\Plugins\Auctipus.lua

Locals: <none>
```
He doesn't have any tradeskills, so I dunno if the rest of skillet is working or not.
I think I had some green iron leggings in the queue for my blacksmith.

**Comment by b-morgan** [comment]
First, I'm not going to do anything with a one-off error on 1.33. Clearly the client was confused by the data the server presented to it. 

Second, Auctipus is a relatively new Auction House addon for which a new Skillet-Classic plugin was developed. With Skillet-Classic-1.37-alpha8, the plugin loads on my system and generates no errors with or without the addon installed. The plugin is referenced in the .toc file and should exist in `...\Addons\Skillet-Classic\Plugins` it exists in my archived copy of 1.36 so if its not there on your system, I suspect you have a bad install.

**Comment by matthewhively** [comment]
Well, I didn't get the auctipus error when loading on the PTR with alpha 8
I'll try on the live realm in a moment.

**Comment by matthewhively** [comment]
Yup, the auctipus error is gone now.
