### ISSUE TITLE
creatall in rogue poisons adds 9999 to queue

### ISSUE THREAD

**Issue by chorp-cpu** [b-morgan/Skillet-Classic#54]
tbc, skillet classic 1.36
i have mats in inventory for 1 instant poison vII and i am at the poison vendor.
hit create all
9999 shows up in the bottom window and it starts creating all of them, shopping window shows up buying one at a time each time it makes a new one.

it keeps repeating this behavior a few times then suddenly stops, deciding it only needs to create one.

**Comment by b-morgan** [comment]
I don't know what is wrong with github but I'm sorry I didn't see this issue until today.

Clicking "Create All" (or "Queue All") for a recipe that uses all vendor bought materials when the vendor has an infinite supply of those materials is probably not a good idea. Even worse is doing this when the Skillet-Classic option "Automatically buy reagents" is checked.

I'll look into adding an "Are you sure" dialog to prevent this "perfect storm" scenario but Skillet-Classic is currently doing exactly what it has been told to do (except the suddenly stopping part which I'm not going to try and figure out).

**Comment by b-morgan** [comment]
A dialog has been added to confirm a Create All or Queue All when an infinite number (9999) can be created from buy reagents from a vendor.
