### ISSUE TITLE
enchanting queues are broken

### ISSUE THREAD

**Issue by chorp-cpu** [b-morgan/Skillet-Classic#56]
tbc v1.36
seclect a recpie (brilliant wizard oil for example)
hit queue one ore more times
you can see the items are added to the shopping list
hit queues button
nothing you queued is listed and there is no way to remove it from the queue
you are stuck with mats in the shopping list forever in a phantom queue you can never delete
the only solution is go into saved variables and delete them

**Comment by b-morgan** [comment]
The Clear button has been enabled when the Queue button is enabled for enchants. The queue is also displayed but cannot be processed.
