### ISSUE TITLE
lua error on creation/queue associated with auctionator plugin

### ISSUE THREAD

**Issue by chorp-cpu** [b-morgan/Skillet-Classic#60]
tbc classic skillet 1.38
auctionator 9.1.8-bcc
I am getting lua errors and unable to create/queue items. tried with eng and alchemy.

50x ...rfaceSkillet-Classic\Plugins\Auctionator-9.1.8.lua:318: attempt to call global 'Atr_GetAuctionBuyout' (a nil value)
[string "@Skillet-Classic\Plugins\Auctionator-9.1.8.lua"]:318: in function `GetExtraText'
[string "@Skillet-Classic\SkilletPlugin.lua"]:148: in function `GetExtraText'
[string "@Skillet-Classic\UI\MainFrame.lua"]:1871: in function `UpdateDetailsWindow'
[string "@Skillet-Classic\UI\MainFrame.lua"]:904: in function `UpdateTradeSkillWindow'
[string "@Skillet-Classic\UI\MainFrame.lua"]:2406: in function `ScrollToSkillIndex'
[string "@Skillet-Classic\Skillet-20502.nil.lua"]:1558: in function `SetSelectedSkill'
[string "@Skillet-Classic\UI\MainFrame.lua"]:2327: in function `SkillButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
skill = <table> {
 numRecursive = 0
 id = "Transmute: Primal Water to Shadow"
 difficulty = "optimal"
 numCraftable = 1
 name = "Transmute: Primal Water to Shadow"
 category = "Elemental"
 tools = <table> {
 }
 numCraftableVendor = 0
 color = <table> {
 }
 numCraftableAlts = 0
}
recipe = <table> {
 vendorOnly = false
 numMade = 1
 name = "Transmute: Primal Water to Shadow"
 reagentData = <table> {
 }
 tools = <table> {
 }
 itemID = 22456
 tradeID = 2259
 spellID = "Transmute: Primal Water to Shadow"
}
label = "|rATR Buyout:"
extra_text = "|cffffffff0|r|cffeda55fc|r"
itemID = 22456
buyout = 0
toConcatLabel = <table> {
}
toConcatExtra = <table> {
}
cost = 0
(for index) = 1
(for limit) = 1
(for step) = 1
i = 1
reagent = <table> {
 id = 21885
 numNeeded = 1
}
needed = 1
id = 21885
itemName = "Primal Water"
value = nil
(*temporary) = nil
(*temporary) = 21885
(*temporary) = "attempt to call global 'Atr_GetAuctionBuyout' (a nil value)"
addonName = "Skillet-Classic"
L = <table> {
 SHOWCRAFTCOUNTSNAME = "Show craftable counts"
 IGNORELISTDESC = "Open the Ignored Materials list frame."
 About = "About"
 From Selection = "From Selection"
 Move to Bottom = "Move to Bottom"
 DISPLAYSHOPPINGLISTATBANKNAME = "Display shopping list at banks"
 click here to add a note = "click here to add a note"
 DISPLAYREQUIREDLEVELDESC = "If the item to be crafted requires a minimum level to use, that level will be displayed along with the recipe"
 Collapse all groups = "Collapse all groups"
 STANDBYNAME = "standby"
 Using Reagent Bank for = "Using Reagent Bank for"
 Filter = "Filter"
 Start = "Start"
 TradeSkillMaster must be in 'WOW UI' mode to use Skillet-Classic = ""
 Rename = "Rename"
 QUEUEGLYPHREAGENTSDESC = "If you can create a reagent needed for the current recipe, and don't have enough, then that reagent will be added to the queue. This option is separate for Glyphs only."
 Sold amount = "Sold amount"
 No headers, try again = "No headers, try again"
 CONFIRMQUEUECLEARNAME = "Use Alt-click to clear queue"
 Select All = "Select All"
 Options = "Options"
 SHOWITEMNOTESTOOLTIPNAME = "Add user specified notes to tooltip"
 Queue = "Queue"
 Set Favorite = "Set Favorite"
 IGNOREBANKEDREAGENTSDESC = "Ignore banked reagents when queuing craftable reagents"
 None = "None"
 CLAMPTOSCREENNAME = "Clamp frames to screen"
 Add to Ignore Materials = "Add to Ignore Materials"
 Press Okay to continue changing professions = "Press Okay to continue changing professions"
 can be created by crafting reagents = "can be created by crafting reagents"
 SORTDESC = "Sort the recipe list from lowest (top) to highest (bottom)"
 USEALTCURRVENDITEMSDESC = "Vendor items bought with alternate currencies are considered vendor supplied."
 have = "have"
 Trained = "Trained"
 DISPLAYSHOPPINGLIST = "Display shopping list at:"
 QUEUEGLYPHREAGENTSNAME = "Queue reagents for Glyphs"
 Tooltip Scale = "Tooltip Scale"
 DISPLAYSHOPPINGLISTATMERCHANTDESC = "Display a shopping list of the items that are needed to craft queued recipes but are not in your bags"
 has cooldown of = "has cooldown of"
 TRADEBUTTONSDESC = "Include TradeSkill buttons in frame"
 Add Recipe to Ignored List = "Add Recipe to Ignored List"
 QUEUEONLYVIEWNAME = "Only show Standalone Queue"
 Inventory = "Inventory"
 Rescan = "Rescan"
 Purchased = "Purchased"
 SCALEDESC = "Scale of the tradeskill window (default 1.0)"
 Save = "Save"
 Changing profession to = "Changing profession to"
 Number of items to queue/create = "Number of items to queue/create"
 Press Process to continue = "Press Process to continue"
 can be created with reagents bought at vendor = "can be created with reagents bought at vendor"
 Using Bank for = "Using Bank for"
 SHOPPINGCLEARDESC = "Clear the shopping list"
 STANDBYDESC = "Toggle standby mode on/off"
 Include guild = "Include guild"
 Flush Recipe Data = "Flush Recipe Data"
 DISPLAYSHOPPINGLISTATAUCTIONNAME = "Display shopping list at auctions"
 VENDORAUTOBUYDESC = "If you have queued recipes and talk to a vendor that sells something needed for those recipes, it will be automatically purchased."
 L

**Comment by b-morgan** [comment]
Sorry I didn't see this issue until today. It has been fixed in [Skillet-Classic-1.40](https://www.curseforge.com/wow/addons/skillet-classic/files/3510681).
