### ISSUE TITLE
Not showing Reagents

### ISSUE THREAD

**Issue by SeriousSeri** [b-morgan/Skillet-Classic#63]
So, in this case, when i select Spicy Hot Talbuk, it won't show that the Recipe needs Hot Spices. Same in other recipies.
In some Recipies, like in Rainbow Fin Albacore, i can't even see the main ingredient. 
I CAN see an Itemlink, which i guess is the missing Stuff, but i does not get resolved: [inventory/bank/craftable] itemID= 33872

**Comment by b-morgan** [comment]
This usually happens the first time you open a profession after logging in. Skillet-Classic can only display the data that the Blizzard API provides. World of Warcraft is a server / client application and the server is responsible for providing data to the client and the Blizzard API tells Skillet-Classic what the client knows. While every attempt has been made to ensure accurate data, when the client API lies to Skillet-Classic, there is little that can be done. Close and open the profession and the problem should go away until your next login.

To attempt to mitigate this problem, there are two chat commands to adjust variables that might help. "/skillet tradewait n" and "/skillet craftwait n" where n is 1-10 (default is 1). Increase n until the problem doesn't occur. If n is too large, the Skillet-Classic frame won't open.

The "craftwait" variable is used for Enchanting only and "tradewait" for all the other professions.

The value for n is highly dependent on your server, the internet and your connection to it, and your client so I can't set a default value higher than 1 in the release. Once you have picked a value it will be remembered and will apply to all characters on that realm.

Let me know if this works (or not) for you.

**Comment by SeriousSeri** [comment]
I opened the Window several times, also with reloading the UI and trying it several times again - with no avail. However, after trying this now again (WoW Client was closed in between) it is working, as you said, after re-opening the window a second time. Weird. Thank You!
