### ISSUE TITLE
Can't open professions unless TSM is disabled

### ISSUE THREAD

**Issue by lvangh** [b-morgan/Skillet-Classic#65]
I have Skillet-Classic intalled and TSM for Som 1.14. 

When I click engineering/first aid/cooking they won't open but the sound plays as if they were. 

If I disable TSM, the skillet versions of the professions work.

**Comment by lvangh** [comment]
Never mind, changed crafting to TSM mode and it works. ty.

**Comment by b-morgan** [comment]
Skillet-Classic and TradeSkillMaster have a tumultuous relationship. The TSM developers refuse to acknowledge that any other trade skill addon exists and have told me so directly.

As stated in the description, Skillet-Classic can be used with TSM for all professions except Enchanting. TSM Crafting UI must be set to native ('TSM4') mode. For Enchanting, use the TSM Crafting UI or disable TSM.

If you are getting TSM errors when Skillet-Classic is open, good luck getting them to fix it.

The same Skillet-Classic code is used on Classic-Era, Burning Crusade Classic, and Season of Mastery. I do not have any characters on Season of Mastery, so I don't know if I can duplicate the errors you are getting and I don't know if there's anything Skillet-Classic can do to eliminate them.
