### ISSUE TITLE
UI not updating skill and such without having to reopen the window every time

### ISSUE THREAD

**Issue by Undeadbear** [b-morgan/Skillet-Classic#67]
I'm using the addon downloaded tough wowup on Classic TBC.

I have to constantly close and reopen the window for it to update.

For example when crafting a bunch of items for skillup, the skill does not change in the window, so I have to reopen the window for that to happen. same when quing and crafting.

Is this a bug or does it not work with classic tbc or is it a setting i've missed?

Regards -Tango

**Comment by b-morgan** [comment]
Skillet-Classic works on Burning Crusade Classic, I do almost all of my development on BCC and I use WowUp.io to update my own system. I have none of the symptoms you describe.

I'm going to guess that another addon is interfering with Skillet-Classic. If you can help me identify that addon, I can see if I can recreate the issue on my system. I'd suggest starting with disabling any addon that has anything to do with crafting. If necessary, disable all addons but Skillet-Classic. If it still happens with only Skillet-Classic enabled, then download the .zip file directly from CurseForge and verify its MD5 signature, delete the `...\Interface\Addons\Skillet` folder and reinstall.

**Comment by b-morgan** [comment]
I can't find an addon named "Actionator". There is, however, an addon named "Auctionator", [https://www.curseforge.com/wow/addons/auctionator](https://www.curseforge.com/wow/addons/auctionator) which is my favorite and definitely works with (and has some integration with) Skillet-Classic.

There are two versions of Auctionator for Burning Crusade Classic. Make sure you only have one of them installed (and for good measure, delete and reinstall it after verifying the MD5 checksum on your download).

I'm sorry you are having issues with getting Skillet-Classic to behave. According to WowUp.io, I have 142 addons installed on my Burning Crusade Classic. It will just take a little bit more detective work on your part to narrow down the issue on your system.

**Comment by chorp-cpu** [comment]
I don't know if it s related, but All the Things (att) addon was causing huge stutters every time you got a skillup (all skills not just tradeskill).  the author alleviated it to a great extent, but not completely.  I believe he said it was related to the skillup triggering a full rescan of something each time.

**Comment by b-morgan** [comment]
There is nothing I can do without additional information so I'm closing this issue. Reopen or open a new issue if more information can be provided.
