### ISSUE TITLE
make create/create all move to the top of the creation queue

### ISSUE THREAD

**Issue by chorp-cpu** [b-morgan/Skillet-Classic#69]
If i have recipies queued that i am waiting on mats for (ah, switching alts, farming, etc.), can you make anything i can currently make via the create/create all button move to the top of the queue or be created right away?  currently it just queues them and sticks them at the bottom of the list.

now what you have to do is clear your queue, create your items/smelt/whateve, then go back and requeue  to get your shopping lists up.

**Comment by b-morgan** [comment]
If you click the Process button, Skillet-Classic will go through the queue skipping entries it can't make until it finds one it can make. You can also right-click on an entry in the queue and select one of Move to Top, Move Up, Move Down, or Move to Bottom.

The same logic applies when the queue is full of things you can't make and you click Create on something you can make.

I believe this solves your issue.
