### ISSUE TITLE
Addon not working in tbc prepatch

### ISSUE THREAD

**Issue by DragunovUA** [b-morgan/Skillet-Classic#7]
![WoWScrnShot_052021_234347](https://user-images.githubusercontent.com/45152251/119046352-427b3a00-b9c5-11eb-9d7c-9271be3ce4ce.jpg)

**Comment by DragunovUA** [comment]
yeah i see notification in chat, but it was all good in classic, zygor+skillet.

**Comment by DragunovUA** [comment]
nvm, same with zygor disabled
![Uploading WoWScrnShot_052121_000553.jpg…]()

**Comment by b-morgan** [comment]
Please try [1.24-alpha](https://www.curseforge.com/wow/addons/skillet-classic/files/3317245) instead. There is only one .zip file and it should work on both `_classic_` (BCC) and `_classic_era_`

I am a little concerned with how you got a Skillet-Classic frame to display without your character name and profession in the title (see below). If it still happens, there's something else FUBAR.

![Skillet-Classic](https://user-images.githubusercontent.com/1547854/119058880-72f2b200-b98c-11eb-9922-43d6cf96db76.jpg)

**Comment by mutantant** [comment]
I have exactly the same issue, same broken window, same lack of info at the top and nothing filled in. Tried removing the saved variables, reinstalling the addon, etc. Using 1.24 Alpha.

It seems the broken, as of yet not updated Missing Tradeskills addon was the culprit. Must be blocking your addon from passing some point as it tries to load it. It doesn't work in TBC anyway, so no harm in disabling it until MTS is updated anyway.

**Comment by DragunovUA** [comment]
yeah, it was MTSL addon, thx for tip!
