### ISSUE TITLE
handle arclight spanner, gyromatic micro-adjuster, blacksmith hammer.

### ISSUE THREAD

**Issue by chorp-cpu** [b-morgan/Skillet-Classic#70]
This is mainly in reference to tbc engineering, but blacksmithing overlaps too, maybe some other skills.

when i create/queue something that requires one of these, can they be added to the shopping list somehow so they are pulled from the bank, or bought in the case of the blacksmith hammer?

**Comment by b-morgan** [comment]
The tools needed to complete a recipe are identified differently than reagents and would require a substantial modification to the database and the logic to treat some of them as items to be fetched, created, or bought.

While I can see advantages to this enhancement, the implementation would be complex and I'm not sure I want to tackle it.

I just carry the needed tools with me all the time and consider the lost inventory slots as a "tax" for choosing those professions.
