### ISSUE TITLE
Skillet  not showing all required mats

### ISSUE THREAD

**Issue by SunTzuTech1** [b-morgan/Skillet-Classic#73]
I am seeing an issue with recipes that have more than a couple of components (primal might, many LW patterns with p5/6 mats) not showing in the panel.   I was crafting a primal might today on the latest build, and it showed the primal mana (in my bag) and the primal earth (not in my bag) but not the other primals (fire, water, air)

**Comment by b-morgan** [comment]
Skillet-Classic gets the material requirements from the Blizzard API. The client side gets the information from the server. Sometimes the server is slow getting the information to the client when you first login. If you close the Skillet-Classic UI and open it again, this issue should clear up.

If that's not the case, then let me know.
