### ISSUE TITLE
Imbued Netherweave Tunic doesn't require 6 imbued netherweave bolts, only makes 2.

### ISSUE THREAD

**Issue by SunTzuTech1** [b-morgan/Skillet-Classic#75]
if I make Imbued Netherweave Tunic, it only makes 2 bolt of imbued netherwave, instead of 6

**Comment by SunTzuTech1** [comment]
bank issue I think.

**Comment by b-morgan** [comment]
By default, Skillet-Classic considers items in your bank when determining what needs to be crafted. There is an option, "Ignore banked reagents" which will change this behavior. If this option doesn't work as expected, please reopen this issue (or start a new one).
