### ISSUE TITLE
Making AddToQueue() public

### ISSUE THREAD

**Issue by Witnessthis** [b-morgan/Skillet-Classic#76]
Please make AddToQueue() public to allow other addons to queue up orders.

In SkilletQueue.lua ->
change 1:
\- local function AddToQueue(command)
\+ function Skillet:AddToQueue(command)

change 2:
\- AddToQueue(command)
\+ Skillet:AddToQueue(command)

**Comment by b-morgan** [comment]
Skillet-Classic-1.46 contains this change.
