### ISSUE TITLE
Enchanting bug - plugin - auctionator

### ISSUE THREAD

**Issue by Raithen88** [b-morgan/Skillet-Classic#83]
If you want to use the auctionator plugin with enchanting, you have the following problem. 

Enchant-Scroll-Item-Names are differently then the so called recipe. Therefore you can't search for lowest prices and compare profits per enchant recipe.

**Comment by b-morgan** [comment]
I have a partial fix for this. In the detail (right) side of Skillet-Classic frame there is an Auctionator button shown when the AH is open. I've modified the plugin to add "Scroll of " to the enchant name and put that in the list I send to Auctionator.

I think I have the recipe (left) side working as well.

**Comment by b-morgan** [comment]
This should work a lot better in [Skillet-Classic-1.48-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/3963905).

**Comment by b-morgan** [comment]
I was lazy and didn't localize the change. Is it just the prefix "Scroll of " that needs to be localized?

There's an alternate solution I could try. I'll build a version with that and post it here for you to try.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.48-alpha2](https://www.curseforge.com/wow/addons/skillet-classic/files/3965565) contains (I hope) a better implementation. First, I localized "Scroll of". You can manually edit `.../Skillet-Classic/Locale/Locale-deDE.lua` and if that works then visit [https://www.curseforge.com/wow/addons/skillet-classic/localization](https://www.curseforge.com/wow/addons/skillet-classic/localization) and update the German translation for everyone else.

Second, if you uncheck the Auctionator plugin option "useSearchExact" then the auctionator search should find the scroll no matter what it is called as long as it contains the enchant name. If you want to leave "useSearchExact" on for other professions, use the option "exceptEnchanting" to turn it off only for Enchanting.

Please still answer my question and request for examples in my previous comment.

**Comment by b-morgan** [comment]
You may have to get [alpha2 from WoWInterface](https://www.wowinterface.com/downloads/dlfile3724/09-03-22-Skillet-Classic-1.48-alpha2-wrath.zip?1662225227) because CurseForge has started rejecting my packages for some unknown reason.

**Comment by b-morgan** [comment]
Skillet-Classic-1.48-beta2 fixes the Auctionator plugin yet again. There will probably be a beta3 because the Auctionator plugin is sort of broken in Classic Era.

**Comment by b-morgan** [comment]
I believe Skillet-Classic-1.48-beta6 has all the changes needed to address the concerns of this issue so I am closing it. If there are additional concerns, reopen it or start a new one.
