### ISSUE TITLE
Smelting menu not opening

### ISSUE THREAD

**Issue by Raulfin** [b-morgan/Skillet-Classic#85]
Was doing some smelting and got my skill from 260ish to 275 and trained Master Miner at the new trainer on Aldor rise in Shatt, after training the smelting window nolonger opens. If i disable Skillet the bliz ui for smelting opens fine, and all other crafting windows open for all other crafts on my alts.
Tried reloading, and chaged toons and restarting game.

**Comment by b-morgan** [comment]
If you don't have any crafting queues or custom groups, logout of WoW and try renaming the global saved variables file Skillet-Classic.lua to Skillet-Classic-old.lua. Login to WoW and see if that fixes the problem toon. If not, let me know and upload the old file (or the new file) here so I can look at it.

**Comment by Raulfin** [comment]
ty it opens now.
Want me to drop the old file on here?

**Comment by b-morgan** [comment]
Sure. Drop the old file on here in case I can see something that I can use to prevent this from happening in the future.

**Comment by Raulfin** [comment]
https://www.dropbox.com/s/4jz4t8swh2d9201/Skillet-Classic.lua.old?dl=0
