### ISSUE TITLE
Shift key to show blizzard frame interferes with modifier based macros

### ISSUE THREAD

**Issue by zackeryps** [b-morgan/Skillet-Classic#9]
Hello,

I have a macro to have all of my skills in one actionbar slot so that I have quick access.
e.g. /cast [mod:shift] Tailoring; Enchanting;
However, Tailoring in this example will always show the blizzard UI because shift is held when the tradeskill spell is 'cast' (by necessity).

Is it possible to have an option to toggle this behavior from Skillet?

**Comment by b-morgan** [comment]
It is possible to create an option but I'm not sure if anyone else would use it.

Is there a reason why you don't change the modifier to something else (like alt)? Skillet-Classic uses shift to open the Blizzard UI and ctrl will clear the player's skillDB (I don't remember why this is done, ATM). 

Both of those modifiers can be changed (or removed) in Skillet.lua and/or SkilletData.lua. Search for IsShiftKeyDown() and/or IsControlKeyDown(). 

Have you looked at the addon [Select](https://www.wowinterface.com/downloads/info11607-Select.html)? Another alternative might be [FlyoutButton-Custom](https://www.curseforge.com/wow/addons/flyoutbutton-custom/files) (Not sure if this one will work on Classic).

**Comment by zackeryps** [comment]
The full macro that I use is:
/cast [mod:alt] First Aid; [mod:ctrl] Cooking; [mod:shift] Tailoring; Enchanting;

So I'm using every modifier key in one button.

Before opening this I tried to edit Skillet.lua line 977 from:
`elseif not IsShiftKeyDown() and not UnitAffectingCombat("player") then`
to:
`elseif  not UnitAffectingCombat("player") then`
but I was still getting the same behavior.
I didn't think to look in SkilletData.lua however.

**Comment by zackeryps** [comment]
Thank you. With your help I managed to get the behavior I was looking for.

For anyone who happens to come across this later, here is what i did:

Skillet.lua line 977: -`elseif not IsShiftKeyDown() and not UnitAffectingCombat("player") then`
Skillet.lua line 977: +`elseif  not UnitAffectingCombat("player") then --not IsShiftKeyDown() and`

SkilletData.lua line 95: -`if IsShiftKeyDown() or UnitAffectingCombat("player") or not tradeID or tradeID == 5419 or tradeID == 53428 then`
SkilletData.lua line 95: +`if  UnitAffectingCombat("player") or not tradeID or tradeID == 5419 or tradeID == 53428 then --IsShiftKeyDown() or`

Skillet.lua lines 996 to 998: commented out
Skillet.lua lines 1444 to 1446: commented out

**Comment by b-morgan** [comment]
FYI, the next release will have a chat command, "/skillet nomodkey", that will toggle the use of Shift and Control during the frame initialization phase (i.e. the part of the process your changes addressed). Shift, Control, and Alt are still used within the Skillet-Classic frame to modify tooltip data and other features.

I also shuffled some code around so that the code you modified is now all in Skillet.lua.

**Comment by zackeryps** [comment]
Thanks for the update.
I noticed that IsSupportedTradeskill(tradeID) in SkilletData.lua is not using the new function that you made.
It still calls IsShiftKeyDown() on line 95 and prevents the skillet window from opening in place of the blizzard window.
Changing this to use your new function self:IsModKey1Down() produces the expected behavior.

**Comment by b-morgan** [comment]
Actually, that's not quite the correct fix. I moved IsSupportedTradeskill to Skillet.lua so the correct fix is to delete the function in SkilletData.lua. Having to test Skillet-Classic on two builds probably contributed to my moving the wrong SkilletData.lua to the repository.

**Comment by zackeryps** [comment]
I tried commenting out the IsSupportedTradeskill function in SkilletData before changing it and I got a lua error when I would try to open the skillet frame.

**Comment by b-morgan** [comment]
In Skillet-Classic-1.26 there are two definitions for the function IsSupportedTradeskill, one in Skillet.lua at line 953 and one in SkilletData.lua at line 94. The second definition in SkilletData.lua will be removed in the next build. 

You can leave it like you have it, update to 1.26 and delete the second definition, or wait for the next build.

![image](https://user-images.githubusercontent.com/1547854/120851420-0a800500-c536-11eb-9ca3-22fec0516990.png)

Sorry for the confusion as I'm not juggling 2 builds for 3 flavors of WoW very well!

**Comment by b-morgan** [comment]
[Skillet-Classic-1.27-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/3338195) (or newer) should be working as expected.

**Comment by zackeryps** [comment]
Thanks for the update.
Love the addon.
