### ISSUE TITLE
Cooking skill window blank

### ISSUE THREAD

**Issue by Velarax** [b-morgan/Skillet-Classic#91]
![WoWScrnShot_090722_113114](https://user-images.githubusercontent.com/92230867/188931762-4b51bb6a-fba7-4c19-9043-7d464bf89bf2.jpg)

I hope you're able to fix this :D

**Comment by b-morgan** [comment]
The orange box above the recipe list says only show recipes that are orange and apparently, you don't have any. Click on the box and select gray instead.

**Comment by Velarax** [comment]
Thanks.  I clicked and unclicked it.   Still nothing.   Finally ended up dumping my cache and my wtf settings and now it's working.  Thanks for your help!

**Comment by b-morgan** [comment]
When you click on that button it should popup a series of buttons of different colors. The one you click on will only show recipes of that color or higher. The order is Orange, Yellow, Green, and then Gray (which is all recipes). You used a larger hammer than necessary but I'm glad its fixed.
