### ISSUE TITLE
Clicking enchant adds the materials to the shopping list, and can't be cleared

### ISSUE THREAD

**Issue by phoenixsmurf** [b-morgan/Skillet-Classic#92]
Steps:
- Open Enchanting Window
- Select an enchant (doesn't matter whether you have the materials or not)
- Click enchant repeatedly
- View shopping list, or go to the bank or the AH

Actual:
- Can't clear the shopping list

Expected:
- That there is a way to clear the shopping list or hidden queue

Images:
<blockquote class="imgur-embed-pub" lang="en" data-id="a/oLKeCGU"  ><a href="//imgur.com/a/oLKeCGU">After enchanting mongoose successfully</a></blockquote>
<blockquote class="imgur-embed-pub" lang="en" data-id="a/WvYY05w"  ><a href="//imgur.com/a/WvYY05w">Enchanted Mongoose a few more times</a></blockquote>

**Comment by b-morgan** [comment]
I've added code to remove all previously queued enchants from the queue when the option "Queue enchant reagents" is not checked. Try [Skillet-Classic-1.48-beta5](https://www.curseforge.com/wow/addons/skillet-classic/files/3973654) and see if it works better for you (when the option isn't checked).

**Comment by b-morgan** [comment]
Use [Skillet-Classic-1.48-beta6](https://www.curseforge.com/wow/addons/skillet-classic/files/3973915) instead.
