### ISSUE TITLE
As of 1.48-beta5 clicking "Enchant" freezes/crashes the game

### ISSUE THREAD

**Issue by rushtothesun** [b-morgan/Skillet-Classic#94]
```
Message: Interface\AddOns\Skillet-Classic\SkilletQueue.lua:514: script ran too long
Time: Thu Sep  8 11:52:13 2022
Count: 1
Stack: Interface\AddOns\Skillet-Classic\SkilletQueue.lua:514: script ran too long
[string "=[C]"]: ?
[string "@Interface\AddOns\Skillet-Classic\SkilletQueue.lua"]:514: in function `EnchantItem'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

```

**Comment by b-morgan** [comment]
I need more information. Please type the following:
```
/skillet debuglogging on
/skillet debuglevel 3
/skillet tabledump on
```
Now reproduce the error and logoff immediately. Upload your character specific saved variables file Skillet-Classic.lua here (you can find that file in `...\World of Warcraft\_classic_\WTF\Account\<your account>\<your realm>\<your character>\SavedVariables`).

After uploading this file (which I need to fix the problem), you can make the problem go away by checking the Skillet-Classic option "Queue Enchant reagents". You can leave debugging enabled as it has a limited buffer and only captures the most recent output or you can turn it off with `/skillet debuglogging off`.

**Comment by rushtothesun** [comment]
https://pastebin.com/raw/VDjZr96q

**Comment by b-morgan** [comment]
[Skillet-Classic-1.48-beta6](https://www.curseforge.com/wow/addons/skillet-classic/files/3973915) has a fix for this issue.
