### ISSUE TITLE
Cloak of Darkness

### ISSUE THREAD

**Issue by Lugnaut** [b-morgan/Skillet-Classic#97]
The reagents listed for Cloak of Darkness aren't correct, it lists 8 heavy knothide leather when its that plus 12 bolts of soulcloth 12 primal shadow and 4primal nether. It has the ATR buyout at roughly the correct price but only shows the 1 reagent for it unlike other recipes.

**Comment by b-morgan** [comment]
Skillet-Classic gets the reagent list from the Blizzard API (on the client). The Blizzard client gets this information from the server and sometimes, the server is slow so the client lies to Skillet-Classic. If you close Skillet-Classic and open it again, there's a good chance that the recipe information will now be correct. If the recipe is still incorrect, let me know.

**Comment by Lugnaut** [comment]
I opened skillet 3 times over than course of 20mins, it was incorrect every time with the same mistake. I will check again once out of queue.

**Comment by b-morgan** [comment]
If you shift-click your leatherworking action bar button to bring up the Blizzard UI, what does the recipe show for reagents? If it is correct, then close the Blizzard UI and click the button to bring up the Skillet-Classic UI. Is it still wrong? If so, please upload your global saved variables file while logged out of WoW and I'll take a look. After uploading that file, try typing `/skillet flushrecipedata` before opening Skillet-Classic. Let me know if that fixes it.

**Comment by Lugnaut** [comment]
the Blizzard UI shows the correct reagents, after checking that the skillet menu shows the correct reagents.

**Comment by b-morgan** [comment]
If this happens again and Blizzard UI is correct and then Skillet-Classic is wrong, either reopen this issue or start a new one.
