### ISSUE TITLE
Profit calculation after AH Tax?

### ISSUE THREAD

**Issue by tywtyw2002** [b-morgan/Skillet-Classic#98]
The profit calculation is seems like the `ATR Buyout - Mats Cost`.

However, if u post the item on AH, the profit is `ATR Buyout * 0.95 -  Mats Cost`.

Is possible to add a option to show profit after the AH TAX.

**Comment by b-morgan** [comment]
I believe the plugin calculation for profit is actually `buyout - cost * markup` where `markup` is adjustable (the default value is 1.05). While not exactly what you are asking for, it should serve the same purpose.

All the pricing information is collected through plugins for Skillet-Classic. These plugins are distributed with Skillet-Classic but most of them were written by other people. I be happy to accept a modified plugin for your AH addon of choice.

**Comment by tywtyw2002** [comment]
I do not think the `buyout - cost * markup` is same to `buyout * (1-tax) - cost`.

For example, the `Ragesteel Helm` on AH is 100G, and the subtotal of mats (cost) is 80G. 
You sold it on AH @ 100G, you will get 100 * 0.95 = 95. (5% AH Tax) 
And you profit is 95 - 80 = 15.

I will submit a PR later.

**Comment by b-morgan** [comment]
You are correct, its not the same. However, it will take some effort to implement the formula you desire.

BTW, for your example, 100 - 80 * 1.05 = 16 calculated profit.

**Comment by b-morgan** [comment]
I have merged your changes and made a couple of minor changes. I moved the option above the sliders instead of below and I added a single constant for the 0.95. Thanks for your efforts.
